version: '3.4'

services:
    nginx_service:
        restart: on-failure:5
        image: nginx_service:0.60-dev
        container_name: dev-nginx_service
        volumes:
            - ./build:/usr/app
        ports:
            - 5000:80
        depends_on:
            - api_service
            - file_service
        links:
            - api_service
            - file_service

    api_service:
        restart: on-failure:5
        image: api_service:0.84
        container_name: dev-api_service
        volumes:
            - ./build/image:/bin/images
        ports:
            - 8080:8080
        depends_on:
            - pro_service
            - file_service
        env_file:
            - .env
        links:
            - pro_service
            - file_service
        environment:
            - PRO_HOST=pro_service
            - FILE_HOST=file_service

    pro_service:
        restart: on-failure:5
        image: pro_service:0.71
        container_name: dev-pro_service
        env_file:
            - .env

    file_service:
        restart: on-failure:5
        image: file_service:0.42
        container_name: dev-file_service
        env_file:
            - .env
        depends_on:
            - minio_service
        links:
            - minio_service

    minio_service:
        image: minio/minio:RELEASE.2022-01-08T03-11-54Z
        container_name: dev-minio_service
        command: server --console-address ":9001" /data/
        ports:
            - "9000:9000"
            - "9001:9001"
        volumes:
            - ./storage:/data
        env_file:
            - .env
        healthcheck:
            test:
                [
                    "CMD",
                    "curl",
                    "-f",
                    "http://localhost:9000/minio/health/live"
                ]
            interval: 30s
            timeout: 20s
            retries: 3
