// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/moment.proto

/*
Package moment_proto is a generated protocol buffer package.

It is generated from these files:
	proto/moment.proto

It has these top-level messages:
	PingRequest
	PingResponse
	Gasket
	FlangeData
	BoltData
	GasketData
	EmbedData
	FlangeRequest
	FlangeResult
	BoltResult
	GasketResult
	EmbedResult
	StrengthResult
	CalcMoment
	CalculatedFlange
	CalcFormulas
	FlangeResponse
*/
package moment_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FlangeData_Type int32

const (
	FlangeData_welded FlangeData_Type = 0
	FlangeData_flat   FlangeData_Type = 1
	FlangeData_free   FlangeData_Type = 2
)

var FlangeData_Type_name = map[int32]string{
	0: "welded",
	1: "flat",
	2: "free",
}
var FlangeData_Type_value = map[string]int32{
	"welded": 0,
	"flat":   1,
	"free":   2,
}

func (x FlangeData_Type) String() string {
	return proto.EnumName(FlangeData_Type_name, int32(x))
}
func (FlangeData_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

type FlangeRequest_Flanges int32

const (
	FlangeRequest_isolated    FlangeRequest_Flanges = 0
	FlangeRequest_nonIsolated FlangeRequest_Flanges = 1
	FlangeRequest_manually    FlangeRequest_Flanges = 2
)

var FlangeRequest_Flanges_name = map[int32]string{
	0: "isolated",
	1: "nonIsolated",
	2: "manually",
}
var FlangeRequest_Flanges_value = map[string]int32{
	"isolated":    0,
	"nonIsolated": 1,
	"manually":    2,
}

func (x FlangeRequest_Flanges) String() string {
	return proto.EnumName(FlangeRequest_Flanges_name, int32(x))
}
func (FlangeRequest_Flanges) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{7, 0} }

type FlangeRequest_Type int32

const (
	FlangeRequest_bolt FlangeRequest_Type = 0
	FlangeRequest_pin  FlangeRequest_Type = 1
)

var FlangeRequest_Type_name = map[int32]string{
	0: "bolt",
	1: "pin",
}
var FlangeRequest_Type_value = map[string]int32{
	"bolt": 0,
	"pin":  1,
}

func (x FlangeRequest_Type) String() string {
	return proto.EnumName(FlangeRequest_Type_name, int32(x))
}
func (FlangeRequest_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{7, 1} }

type FlangeRequest_Condition int32

const (
	FlangeRequest_uncontrollable  FlangeRequest_Condition = 0
	FlangeRequest_controllable    FlangeRequest_Condition = 1
	FlangeRequest_controllablePin FlangeRequest_Condition = 2
)

var FlangeRequest_Condition_name = map[int32]string{
	0: "uncontrollable",
	1: "controllable",
	2: "controllablePin",
}
var FlangeRequest_Condition_value = map[string]int32{
	"uncontrollable":  0,
	"controllable":    1,
	"controllablePin": 2,
}

func (x FlangeRequest_Condition) String() string {
	return proto.EnumName(FlangeRequest_Condition_name, int32(x))
}
func (FlangeRequest_Condition) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{7, 2} }

type FlangeRequest_Calcutation int32

const (
	FlangeRequest_basis    FlangeRequest_Calcutation = 0
	FlangeRequest_strength FlangeRequest_Calcutation = 1
)

var FlangeRequest_Calcutation_name = map[int32]string{
	0: "basis",
	1: "strength",
}
var FlangeRequest_Calcutation_value = map[string]int32{
	"basis":    0,
	"strength": 1,
}

func (x FlangeRequest_Calcutation) String() string {
	return proto.EnumName(FlangeRequest_Calcutation_name, int32(x))
}
func (FlangeRequest_Calcutation) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{7, 3} }

type PingRequest struct {
}

func (m *PingRequest) Reset()                    { *m = PingRequest{} }
func (m *PingRequest) String() string            { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()               {}
func (*PingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PingResponse struct {
	Ping string `protobuf:"bytes,1,opt,name=ping" json:"ping,omitempty"`
}

func (m *PingResponse) Reset()                    { *m = PingResponse{} }
func (m *PingResponse) String() string            { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()               {}
func (*PingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PingResponse) GetPing() string {
	if m != nil {
		return m.Ping
	}
	return ""
}

type Gasket struct {
}

func (m *Gasket) Reset()                    { *m = Gasket{} }
func (m *Gasket) String() string            { return proto.CompactTextString(m) }
func (*Gasket) ProtoMessage()               {}
func (*Gasket) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type FlangeData struct {
	Type       FlangeData_Type `protobuf:"varint,1,opt,name=type,enum=moment_proto.FlangeData_Type" json:"type,omitempty"`
	StandartId string          `protobuf:"bytes,2,opt,name=standartId" json:"standartId,omitempty"`
	MarkId     string          `protobuf:"bytes,3,opt,name=markId" json:"markId,omitempty"`
	Dy         int32           `protobuf:"varint,4,opt,name=dy" json:"dy,omitempty"`
	Py         float64         `protobuf:"fixed64,5,opt,name=py" json:"py,omitempty"`
	Corrosion  float64         `protobuf:"fixed64,6,opt,name=corrosion" json:"corrosion,omitempty"`
}

func (m *FlangeData) Reset()                    { *m = FlangeData{} }
func (m *FlangeData) String() string            { return proto.CompactTextString(m) }
func (*FlangeData) ProtoMessage()               {}
func (*FlangeData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *FlangeData) GetType() FlangeData_Type {
	if m != nil {
		return m.Type
	}
	return FlangeData_welded
}

func (m *FlangeData) GetStandartId() string {
	if m != nil {
		return m.StandartId
	}
	return ""
}

func (m *FlangeData) GetMarkId() string {
	if m != nil {
		return m.MarkId
	}
	return ""
}

func (m *FlangeData) GetDy() int32 {
	if m != nil {
		return m.Dy
	}
	return 0
}

func (m *FlangeData) GetPy() float64 {
	if m != nil {
		return m.Py
	}
	return 0
}

func (m *FlangeData) GetCorrosion() float64 {
	if m != nil {
		return m.Corrosion
	}
	return 0
}

type BoltData struct {
	MarkId string `protobuf:"bytes,1,opt,name=markId" json:"markId,omitempty"`
}

func (m *BoltData) Reset()                    { *m = BoltData{} }
func (m *BoltData) String() string            { return proto.CompactTextString(m) }
func (*BoltData) ProtoMessage()               {}
func (*BoltData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *BoltData) GetMarkId() string {
	if m != nil {
		return m.MarkId
	}
	return ""
}

type GasketData struct {
	GasketId  string  `protobuf:"bytes,1,opt,name=gasketId" json:"gasketId,omitempty"`
	EnvId     string  `protobuf:"bytes,2,opt,name=envId" json:"envId,omitempty"`
	Thickness float64 `protobuf:"fixed64,3,opt,name=thickness" json:"thickness,omitempty"`
	DOut      float64 `protobuf:"fixed64,4,opt,name=d_out,json=dOut" json:"d_out,omitempty"`
	DIn       float64 `protobuf:"fixed64,5,opt,name=d_in,json=dIn" json:"d_in,omitempty"`
}

func (m *GasketData) Reset()                    { *m = GasketData{} }
func (m *GasketData) String() string            { return proto.CompactTextString(m) }
func (*GasketData) ProtoMessage()               {}
func (*GasketData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GasketData) GetGasketId() string {
	if m != nil {
		return m.GasketId
	}
	return ""
}

func (m *GasketData) GetEnvId() string {
	if m != nil {
		return m.EnvId
	}
	return ""
}

func (m *GasketData) GetThickness() float64 {
	if m != nil {
		return m.Thickness
	}
	return 0
}

func (m *GasketData) GetDOut() float64 {
	if m != nil {
		return m.DOut
	}
	return 0
}

func (m *GasketData) GetDIn() float64 {
	if m != nil {
		return m.DIn
	}
	return 0
}

type EmbedData struct {
	MarkId    string  `protobuf:"bytes,1,opt,name=markId" json:"markId,omitempty"`
	Thickness float64 `protobuf:"fixed64,2,opt,name=thickness" json:"thickness,omitempty"`
}

func (m *EmbedData) Reset()                    { *m = EmbedData{} }
func (m *EmbedData) String() string            { return proto.CompactTextString(m) }
func (*EmbedData) ProtoMessage()               {}
func (*EmbedData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *EmbedData) GetMarkId() string {
	if m != nil {
		return m.MarkId
	}
	return ""
}

func (m *EmbedData) GetThickness() float64 {
	if m != nil {
		return m.Thickness
	}
	return 0
}

type FlangeRequest struct {
	Pressure       float64                   `protobuf:"fixed64,1,opt,name=pressure" json:"pressure,omitempty"`
	AxialForce     int32                     `protobuf:"varint,2,opt,name=axialForce" json:"axialForce,omitempty"`
	BendingMoment  int32                     `protobuf:"varint,3,opt,name=bendingMoment" json:"bendingMoment,omitempty"`
	Temp           float64                   `protobuf:"fixed64,4,opt,name=temp" json:"temp,omitempty"`
	IsWork         bool                      `protobuf:"varint,5,opt,name=isWork" json:"isWork,omitempty"`
	Flanges        FlangeRequest_Flanges     `protobuf:"varint,6,opt,name=flanges,enum=moment_proto.FlangeRequest_Flanges" json:"flanges,omitempty"`
	IsSameFlange   bool                      `protobuf:"varint,7,opt,name=isSameFlange" json:"isSameFlange,omitempty"`
	IsEmbedded     bool                      `protobuf:"varint,8,opt,name=isEmbedded" json:"isEmbedded,omitempty"`
	Type           FlangeRequest_Type        `protobuf:"varint,9,opt,name=type,enum=moment_proto.FlangeRequest_Type" json:"type,omitempty"`
	Condition      FlangeRequest_Condition   `protobuf:"varint,10,opt,name=condition,enum=moment_proto.FlangeRequest_Condition" json:"condition,omitempty"`
	Calculation    FlangeRequest_Calcutation `protobuf:"varint,11,opt,name=calculation,enum=moment_proto.FlangeRequest_Calcutation" json:"calculation,omitempty"`
	FlangesData    []*FlangeData             `protobuf:"bytes,12,rep,name=flangesData" json:"flangesData,omitempty"`
	Bolts          *BoltData                 `protobuf:"bytes,13,opt,name=bolts" json:"bolts,omitempty"`
	Gasket         *GasketData               `protobuf:"bytes,14,opt,name=gasket" json:"gasket,omitempty"`
	Embed          *EmbedData                `protobuf:"bytes,15,opt,name=embed" json:"embed,omitempty"`
	IsNeedFormulas bool                      `protobuf:"varint,16,opt,name=isNeedFormulas" json:"isNeedFormulas,omitempty"`
}

func (m *FlangeRequest) Reset()                    { *m = FlangeRequest{} }
func (m *FlangeRequest) String() string            { return proto.CompactTextString(m) }
func (*FlangeRequest) ProtoMessage()               {}
func (*FlangeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *FlangeRequest) GetPressure() float64 {
	if m != nil {
		return m.Pressure
	}
	return 0
}

func (m *FlangeRequest) GetAxialForce() int32 {
	if m != nil {
		return m.AxialForce
	}
	return 0
}

func (m *FlangeRequest) GetBendingMoment() int32 {
	if m != nil {
		return m.BendingMoment
	}
	return 0
}

func (m *FlangeRequest) GetTemp() float64 {
	if m != nil {
		return m.Temp
	}
	return 0
}

func (m *FlangeRequest) GetIsWork() bool {
	if m != nil {
		return m.IsWork
	}
	return false
}

func (m *FlangeRequest) GetFlanges() FlangeRequest_Flanges {
	if m != nil {
		return m.Flanges
	}
	return FlangeRequest_isolated
}

func (m *FlangeRequest) GetIsSameFlange() bool {
	if m != nil {
		return m.IsSameFlange
	}
	return false
}

func (m *FlangeRequest) GetIsEmbedded() bool {
	if m != nil {
		return m.IsEmbedded
	}
	return false
}

func (m *FlangeRequest) GetType() FlangeRequest_Type {
	if m != nil {
		return m.Type
	}
	return FlangeRequest_bolt
}

func (m *FlangeRequest) GetCondition() FlangeRequest_Condition {
	if m != nil {
		return m.Condition
	}
	return FlangeRequest_uncontrollable
}

func (m *FlangeRequest) GetCalculation() FlangeRequest_Calcutation {
	if m != nil {
		return m.Calculation
	}
	return FlangeRequest_basis
}

func (m *FlangeRequest) GetFlangesData() []*FlangeData {
	if m != nil {
		return m.FlangesData
	}
	return nil
}

func (m *FlangeRequest) GetBolts() *BoltData {
	if m != nil {
		return m.Bolts
	}
	return nil
}

func (m *FlangeRequest) GetGasket() *GasketData {
	if m != nil {
		return m.Gasket
	}
	return nil
}

func (m *FlangeRequest) GetEmbed() *EmbedData {
	if m != nil {
		return m.Embed
	}
	return nil
}

func (m *FlangeRequest) GetIsNeedFormulas() bool {
	if m != nil {
		return m.IsNeedFormulas
	}
	return false
}

type FlangeResult struct {
	DOut         float64 `protobuf:"fixed64,1,opt,name=dOut" json:"dOut,omitempty"`
	D            float64 `protobuf:"fixed64,2,opt,name=d" json:"d,omitempty"`
	Dk           float64 `protobuf:"fixed64,3,opt,name=dk" json:"dk,omitempty"`
	Dnk          float64 `protobuf:"fixed64,4,opt,name=dnk" json:"dnk,omitempty"`
	Ds           float64 `protobuf:"fixed64,5,opt,name=ds" json:"ds,omitempty"`
	H            float64 `protobuf:"fixed64,6,opt,name=h" json:"h,omitempty"`
	Hk           float64 `protobuf:"fixed64,7,opt,name=hk" json:"hk,omitempty"`
	S0           float64 `protobuf:"fixed64,8,opt,name=s0" json:"s0,omitempty"`
	S1           float64 `protobuf:"fixed64,9,opt,name=s1" json:"s1,omitempty"`
	L            float64 `protobuf:"fixed64,10,opt,name=l" json:"l,omitempty"`
	D6           float64 `protobuf:"fixed64,11,opt,name=d6" json:"d6,omitempty"`
	C            float64 `protobuf:"fixed64,12,opt,name=c" json:"c,omitempty"`
	Tf           float64 `protobuf:"fixed64,13,opt,name=tf" json:"tf,omitempty"`
	Tk           float64 `protobuf:"fixed64,14,opt,name=tk" json:"tk,omitempty"`
	AlphaK       float64 `protobuf:"fixed64,15,opt,name=alphaK" json:"alphaK,omitempty"`
	EpsilonKAt20 float64 `protobuf:"fixed64,16,opt,name=epsilonKAt20" json:"epsilonKAt20,omitempty"`
	EpsilonK     float64 `protobuf:"fixed64,17,opt,name=epsilonK" json:"epsilonK,omitempty"`
	SigmaKAt20   float64 `protobuf:"fixed64,18,opt,name=sigmaKAt20" json:"sigmaKAt20,omitempty"`
	SigmaK       float64 `protobuf:"fixed64,19,opt,name=sigmaK" json:"sigmaK,omitempty"`
	AlphaF       float64 `protobuf:"fixed64,20,opt,name=alphaF" json:"alphaF,omitempty"`
	EpsilonAt20  float64 `protobuf:"fixed64,21,opt,name=epsilonAt20" json:"epsilonAt20,omitempty"`
	Epsilon      float64 `protobuf:"fixed64,22,opt,name=epsilon" json:"epsilon,omitempty"`
	SigmaAt20    float64 `protobuf:"fixed64,23,opt,name=sigmaAt20" json:"sigmaAt20,omitempty"`
	Sigma        float64 `protobuf:"fixed64,24,opt,name=sigma" json:"sigma,omitempty"`
	SigmaM       float64 `protobuf:"fixed64,25,opt,name=sigmaM" json:"sigmaM,omitempty"`
	SigmaMAt20   float64 `protobuf:"fixed64,26,opt,name=sigmaMAt20" json:"sigmaMAt20,omitempty"`
	SigmaR       float64 `protobuf:"fixed64,27,opt,name=sigmaR" json:"sigmaR,omitempty"`
	SigmaRAt20   float64 `protobuf:"fixed64,28,opt,name=sigmaRAt20" json:"sigmaRAt20,omitempty"`
	Material     string  `protobuf:"bytes,29,opt,name=material" json:"material,omitempty"`
}

func (m *FlangeResult) Reset()                    { *m = FlangeResult{} }
func (m *FlangeResult) String() string            { return proto.CompactTextString(m) }
func (*FlangeResult) ProtoMessage()               {}
func (*FlangeResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *FlangeResult) GetDOut() float64 {
	if m != nil {
		return m.DOut
	}
	return 0
}

func (m *FlangeResult) GetD() float64 {
	if m != nil {
		return m.D
	}
	return 0
}

func (m *FlangeResult) GetDk() float64 {
	if m != nil {
		return m.Dk
	}
	return 0
}

func (m *FlangeResult) GetDnk() float64 {
	if m != nil {
		return m.Dnk
	}
	return 0
}

func (m *FlangeResult) GetDs() float64 {
	if m != nil {
		return m.Ds
	}
	return 0
}

func (m *FlangeResult) GetH() float64 {
	if m != nil {
		return m.H
	}
	return 0
}

func (m *FlangeResult) GetHk() float64 {
	if m != nil {
		return m.Hk
	}
	return 0
}

func (m *FlangeResult) GetS0() float64 {
	if m != nil {
		return m.S0
	}
	return 0
}

func (m *FlangeResult) GetS1() float64 {
	if m != nil {
		return m.S1
	}
	return 0
}

func (m *FlangeResult) GetL() float64 {
	if m != nil {
		return m.L
	}
	return 0
}

func (m *FlangeResult) GetD6() float64 {
	if m != nil {
		return m.D6
	}
	return 0
}

func (m *FlangeResult) GetC() float64 {
	if m != nil {
		return m.C
	}
	return 0
}

func (m *FlangeResult) GetTf() float64 {
	if m != nil {
		return m.Tf
	}
	return 0
}

func (m *FlangeResult) GetTk() float64 {
	if m != nil {
		return m.Tk
	}
	return 0
}

func (m *FlangeResult) GetAlphaK() float64 {
	if m != nil {
		return m.AlphaK
	}
	return 0
}

func (m *FlangeResult) GetEpsilonKAt20() float64 {
	if m != nil {
		return m.EpsilonKAt20
	}
	return 0
}

func (m *FlangeResult) GetEpsilonK() float64 {
	if m != nil {
		return m.EpsilonK
	}
	return 0
}

func (m *FlangeResult) GetSigmaKAt20() float64 {
	if m != nil {
		return m.SigmaKAt20
	}
	return 0
}

func (m *FlangeResult) GetSigmaK() float64 {
	if m != nil {
		return m.SigmaK
	}
	return 0
}

func (m *FlangeResult) GetAlphaF() float64 {
	if m != nil {
		return m.AlphaF
	}
	return 0
}

func (m *FlangeResult) GetEpsilonAt20() float64 {
	if m != nil {
		return m.EpsilonAt20
	}
	return 0
}

func (m *FlangeResult) GetEpsilon() float64 {
	if m != nil {
		return m.Epsilon
	}
	return 0
}

func (m *FlangeResult) GetSigmaAt20() float64 {
	if m != nil {
		return m.SigmaAt20
	}
	return 0
}

func (m *FlangeResult) GetSigma() float64 {
	if m != nil {
		return m.Sigma
	}
	return 0
}

func (m *FlangeResult) GetSigmaM() float64 {
	if m != nil {
		return m.SigmaM
	}
	return 0
}

func (m *FlangeResult) GetSigmaMAt20() float64 {
	if m != nil {
		return m.SigmaMAt20
	}
	return 0
}

func (m *FlangeResult) GetSigmaR() float64 {
	if m != nil {
		return m.SigmaR
	}
	return 0
}

func (m *FlangeResult) GetSigmaRAt20() float64 {
	if m != nil {
		return m.SigmaRAt20
	}
	return 0
}

func (m *FlangeResult) GetMaterial() string {
	if m != nil {
		return m.Material
	}
	return ""
}

type BoltResult struct {
	Diameter    int32   `protobuf:"varint,1,opt,name=diameter" json:"diameter,omitempty"`
	Area        float64 `protobuf:"fixed64,2,opt,name=area" json:"area,omitempty"`
	Count       int32   `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`
	Lenght      float64 `protobuf:"fixed64,4,opt,name=lenght" json:"lenght,omitempty"`
	Temp        float64 `protobuf:"fixed64,5,opt,name=temp" json:"temp,omitempty"`
	Alpha       float64 `protobuf:"fixed64,6,opt,name=alpha" json:"alpha,omitempty"`
	EpsilonAt20 float64 `protobuf:"fixed64,7,opt,name=epsilonAt20" json:"epsilonAt20,omitempty"`
	Epsilon     float64 `protobuf:"fixed64,8,opt,name=epsilon" json:"epsilon,omitempty"`
	SigmaAt20   float64 `protobuf:"fixed64,9,opt,name=sigmaAt20" json:"sigmaAt20,omitempty"`
	Sigma       float64 `protobuf:"fixed64,10,opt,name=sigma" json:"sigma,omitempty"`
}

func (m *BoltResult) Reset()                    { *m = BoltResult{} }
func (m *BoltResult) String() string            { return proto.CompactTextString(m) }
func (*BoltResult) ProtoMessage()               {}
func (*BoltResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *BoltResult) GetDiameter() int32 {
	if m != nil {
		return m.Diameter
	}
	return 0
}

func (m *BoltResult) GetArea() float64 {
	if m != nil {
		return m.Area
	}
	return 0
}

func (m *BoltResult) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *BoltResult) GetLenght() float64 {
	if m != nil {
		return m.Lenght
	}
	return 0
}

func (m *BoltResult) GetTemp() float64 {
	if m != nil {
		return m.Temp
	}
	return 0
}

func (m *BoltResult) GetAlpha() float64 {
	if m != nil {
		return m.Alpha
	}
	return 0
}

func (m *BoltResult) GetEpsilonAt20() float64 {
	if m != nil {
		return m.EpsilonAt20
	}
	return 0
}

func (m *BoltResult) GetEpsilon() float64 {
	if m != nil {
		return m.Epsilon
	}
	return 0
}

func (m *BoltResult) GetSigmaAt20() float64 {
	if m != nil {
		return m.SigmaAt20
	}
	return 0
}

func (m *BoltResult) GetSigma() float64 {
	if m != nil {
		return m.Sigma
	}
	return 0
}

type GasketResult struct {
	GasketId        string  `protobuf:"bytes,1,opt,name=gasketId" json:"gasketId,omitempty"`
	EnvId           string  `protobuf:"bytes,2,opt,name=envId" json:"envId,omitempty"`
	Thickness       float64 `protobuf:"fixed64,3,opt,name=thickness" json:"thickness,omitempty"`
	DOut            float64 `protobuf:"fixed64,4,opt,name=d_out,json=dOut" json:"d_out,omitempty"`
	Width           float64 `protobuf:"fixed64,5,opt,name=width" json:"width,omitempty"`
	M               float64 `protobuf:"fixed64,6,opt,name=m" json:"m,omitempty"`
	Pres            float64 `protobuf:"fixed64,7,opt,name=pres" json:"pres,omitempty"`
	Compression     float64 `protobuf:"fixed64,8,opt,name=compression" json:"compression,omitempty"`
	Epsilon         float64 `protobuf:"fixed64,9,opt,name=epsilon" json:"epsilon,omitempty"`
	PermissiblePres float64 `protobuf:"fixed64,10,opt,name=permissiblePres" json:"permissiblePres,omitempty"`
}

func (m *GasketResult) Reset()                    { *m = GasketResult{} }
func (m *GasketResult) String() string            { return proto.CompactTextString(m) }
func (*GasketResult) ProtoMessage()               {}
func (*GasketResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *GasketResult) GetGasketId() string {
	if m != nil {
		return m.GasketId
	}
	return ""
}

func (m *GasketResult) GetEnvId() string {
	if m != nil {
		return m.EnvId
	}
	return ""
}

func (m *GasketResult) GetThickness() float64 {
	if m != nil {
		return m.Thickness
	}
	return 0
}

func (m *GasketResult) GetDOut() float64 {
	if m != nil {
		return m.DOut
	}
	return 0
}

func (m *GasketResult) GetWidth() float64 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *GasketResult) GetM() float64 {
	if m != nil {
		return m.M
	}
	return 0
}

func (m *GasketResult) GetPres() float64 {
	if m != nil {
		return m.Pres
	}
	return 0
}

func (m *GasketResult) GetCompression() float64 {
	if m != nil {
		return m.Compression
	}
	return 0
}

func (m *GasketResult) GetEpsilon() float64 {
	if m != nil {
		return m.Epsilon
	}
	return 0
}

func (m *GasketResult) GetPermissiblePres() float64 {
	if m != nil {
		return m.PermissiblePres
	}
	return 0
}

type EmbedResult struct {
	MarkId    string  `protobuf:"bytes,1,opt,name=markId" json:"markId,omitempty"`
	Thickness float64 `protobuf:"fixed64,2,opt,name=thickness" json:"thickness,omitempty"`
	Alpfa     float64 `protobuf:"fixed64,3,opt,name=alpfa" json:"alpfa,omitempty"`
	Temp      float64 `protobuf:"fixed64,4,opt,name=temp" json:"temp,omitempty"`
}

func (m *EmbedResult) Reset()                    { *m = EmbedResult{} }
func (m *EmbedResult) String() string            { return proto.CompactTextString(m) }
func (*EmbedResult) ProtoMessage()               {}
func (*EmbedResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *EmbedResult) GetMarkId() string {
	if m != nil {
		return m.MarkId
	}
	return ""
}

func (m *EmbedResult) GetThickness() float64 {
	if m != nil {
		return m.Thickness
	}
	return 0
}

func (m *EmbedResult) GetAlpfa() float64 {
	if m != nil {
		return m.Alpfa
	}
	return 0
}

func (m *EmbedResult) GetTemp() float64 {
	if m != nil {
		return m.Temp
	}
	return 0
}

type StrengthResult struct {
	Mkp       float64 `protobuf:"fixed64,1,opt,name=Mkp,json=mkp" json:"Mkp,omitempty"`
	Mkp1      float64 `protobuf:"fixed64,2,opt,name=Mkp1,json=mkp1" json:"Mkp1,omitempty"`
	Cf        float64 `protobuf:"fixed64,3,opt,name=Cf,json=cf" json:"Cf,omitempty"`
	Dzv       float64 `protobuf:"fixed64,4,opt,name=Dzv,json=dzv" json:"Dzv,omitempty"`
	MM        float64 `protobuf:"fixed64,5,opt,name=MM,json=mM" json:"MM,omitempty"`
	MMk       float64 `protobuf:"fixed64,6,opt,name=MMk,json=mMk" json:"MMk,omitempty"`
	Mpk       float64 `protobuf:"fixed64,7,opt,name=Mpk,json=mpk" json:"Mpk,omitempty"`
	Mp        float64 `protobuf:"fixed64,8,opt,name=Mp,json=mp" json:"Mp,omitempty"`
	SigmaM1   float64 `protobuf:"fixed64,9,opt,name=sigmaM1" json:"sigmaM1,omitempty"`
	SigmaM0   float64 `protobuf:"fixed64,10,opt,name=sigmaM0" json:"sigmaM0,omitempty"`
	SigmaT    float64 `protobuf:"fixed64,11,opt,name=sigmaT" json:"sigmaT,omitempty"`
	SigmaR    float64 `protobuf:"fixed64,12,opt,name=sigmaR" json:"sigmaR,omitempty"`
	SigmaTp   float64 `protobuf:"fixed64,13,opt,name=sigmaTp" json:"sigmaTp,omitempty"`
	SigmaRp   float64 `protobuf:"fixed64,14,opt,name=sigmaRp" json:"sigmaRp,omitempty"`
	SigmaK    float64 `protobuf:"fixed64,15,opt,name=sigmaK" json:"sigmaK,omitempty"`
	SigmaP1   float64 `protobuf:"fixed64,16,opt,name=sigmaP1" json:"sigmaP1,omitempty"`
	SigmaP0   float64 `protobuf:"fixed64,17,opt,name=sigmaP0" json:"sigmaP0,omitempty"`
	SigmaMp   float64 `protobuf:"fixed64,18,opt,name=sigmaMp" json:"sigmaMp,omitempty"`
	SigmaMpm  float64 `protobuf:"fixed64,19,opt,name=sigmaMpm" json:"sigmaMpm,omitempty"`
	SigmaMp0  float64 `protobuf:"fixed64,20,opt,name=sigmaMp0" json:"sigmaMp0,omitempty"`
	SigmaMpm0 float64 `protobuf:"fixed64,21,opt,name=sigmaMpm0" json:"sigmaMpm0,omitempty"`
	SigmaMop  float64 `protobuf:"fixed64,22,opt,name=sigmaMop" json:"sigmaMop,omitempty"`
	SigmaKp   float64 `protobuf:"fixed64,23,opt,name=sigmaKp" json:"sigmaKp,omitempty"`
	Teta      float64 `protobuf:"fixed64,24,opt,name=teta" json:"teta,omitempty"`
	DTeta     float64 `protobuf:"fixed64,25,opt,name=dTeta" json:"dTeta,omitempty"`
	DTetaK    float64 `protobuf:"fixed64,26,opt,name=dTetaK" json:"dTetaK,omitempty"`
	TetaK     float64 `protobuf:"fixed64,27,opt,name=tetaK" json:"tetaK,omitempty"`
	Max1      float64 `protobuf:"fixed64,28,opt,name=Max1,json=max1" json:"Max1,omitempty"`
	Max2      float64 `protobuf:"fixed64,29,opt,name=Max2,json=max2" json:"Max2,omitempty"`
	Max3      float64 `protobuf:"fixed64,30,opt,name=Max3,json=max3" json:"Max3,omitempty"`
	Max4      float64 `protobuf:"fixed64,31,opt,name=Max4,json=max4" json:"Max4,omitempty"`
	Max5      float64 `protobuf:"fixed64,32,opt,name=Max5,json=max5" json:"Max5,omitempty"`
	Max6      float64 `protobuf:"fixed64,33,opt,name=Max6,json=max6" json:"Max6,omitempty"`
	Max7      float64 `protobuf:"fixed64,34,opt,name=Max7,json=max7" json:"Max7,omitempty"`
	Max8      float64 `protobuf:"fixed64,35,opt,name=Max8,json=max8" json:"Max8,omitempty"`
	Max9      float64 `protobuf:"fixed64,36,opt,name=Max9,json=max9" json:"Max9,omitempty"`
	Max10     float64 `protobuf:"fixed64,37,opt,name=Max10,json=max10" json:"Max10,omitempty"`
	Max11     float64 `protobuf:"fixed64,38,opt,name=Max11,json=max11" json:"Max11,omitempty"`
}

func (m *StrengthResult) Reset()                    { *m = StrengthResult{} }
func (m *StrengthResult) String() string            { return proto.CompactTextString(m) }
func (*StrengthResult) ProtoMessage()               {}
func (*StrengthResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *StrengthResult) GetMkp() float64 {
	if m != nil {
		return m.Mkp
	}
	return 0
}

func (m *StrengthResult) GetMkp1() float64 {
	if m != nil {
		return m.Mkp1
	}
	return 0
}

func (m *StrengthResult) GetCf() float64 {
	if m != nil {
		return m.Cf
	}
	return 0
}

func (m *StrengthResult) GetDzv() float64 {
	if m != nil {
		return m.Dzv
	}
	return 0
}

func (m *StrengthResult) GetMM() float64 {
	if m != nil {
		return m.MM
	}
	return 0
}

func (m *StrengthResult) GetMMk() float64 {
	if m != nil {
		return m.MMk
	}
	return 0
}

func (m *StrengthResult) GetMpk() float64 {
	if m != nil {
		return m.Mpk
	}
	return 0
}

func (m *StrengthResult) GetMp() float64 {
	if m != nil {
		return m.Mp
	}
	return 0
}

func (m *StrengthResult) GetSigmaM1() float64 {
	if m != nil {
		return m.SigmaM1
	}
	return 0
}

func (m *StrengthResult) GetSigmaM0() float64 {
	if m != nil {
		return m.SigmaM0
	}
	return 0
}

func (m *StrengthResult) GetSigmaT() float64 {
	if m != nil {
		return m.SigmaT
	}
	return 0
}

func (m *StrengthResult) GetSigmaR() float64 {
	if m != nil {
		return m.SigmaR
	}
	return 0
}

func (m *StrengthResult) GetSigmaTp() float64 {
	if m != nil {
		return m.SigmaTp
	}
	return 0
}

func (m *StrengthResult) GetSigmaRp() float64 {
	if m != nil {
		return m.SigmaRp
	}
	return 0
}

func (m *StrengthResult) GetSigmaK() float64 {
	if m != nil {
		return m.SigmaK
	}
	return 0
}

func (m *StrengthResult) GetSigmaP1() float64 {
	if m != nil {
		return m.SigmaP1
	}
	return 0
}

func (m *StrengthResult) GetSigmaP0() float64 {
	if m != nil {
		return m.SigmaP0
	}
	return 0
}

func (m *StrengthResult) GetSigmaMp() float64 {
	if m != nil {
		return m.SigmaMp
	}
	return 0
}

func (m *StrengthResult) GetSigmaMpm() float64 {
	if m != nil {
		return m.SigmaMpm
	}
	return 0
}

func (m *StrengthResult) GetSigmaMp0() float64 {
	if m != nil {
		return m.SigmaMp0
	}
	return 0
}

func (m *StrengthResult) GetSigmaMpm0() float64 {
	if m != nil {
		return m.SigmaMpm0
	}
	return 0
}

func (m *StrengthResult) GetSigmaMop() float64 {
	if m != nil {
		return m.SigmaMop
	}
	return 0
}

func (m *StrengthResult) GetSigmaKp() float64 {
	if m != nil {
		return m.SigmaKp
	}
	return 0
}

func (m *StrengthResult) GetTeta() float64 {
	if m != nil {
		return m.Teta
	}
	return 0
}

func (m *StrengthResult) GetDTeta() float64 {
	if m != nil {
		return m.DTeta
	}
	return 0
}

func (m *StrengthResult) GetDTetaK() float64 {
	if m != nil {
		return m.DTetaK
	}
	return 0
}

func (m *StrengthResult) GetTetaK() float64 {
	if m != nil {
		return m.TetaK
	}
	return 0
}

func (m *StrengthResult) GetMax1() float64 {
	if m != nil {
		return m.Max1
	}
	return 0
}

func (m *StrengthResult) GetMax2() float64 {
	if m != nil {
		return m.Max2
	}
	return 0
}

func (m *StrengthResult) GetMax3() float64 {
	if m != nil {
		return m.Max3
	}
	return 0
}

func (m *StrengthResult) GetMax4() float64 {
	if m != nil {
		return m.Max4
	}
	return 0
}

func (m *StrengthResult) GetMax5() float64 {
	if m != nil {
		return m.Max5
	}
	return 0
}

func (m *StrengthResult) GetMax6() float64 {
	if m != nil {
		return m.Max6
	}
	return 0
}

func (m *StrengthResult) GetMax7() float64 {
	if m != nil {
		return m.Max7
	}
	return 0
}

func (m *StrengthResult) GetMax8() float64 {
	if m != nil {
		return m.Max8
	}
	return 0
}

func (m *StrengthResult) GetMax9() float64 {
	if m != nil {
		return m.Max9
	}
	return 0
}

func (m *StrengthResult) GetMax10() float64 {
	if m != nil {
		return m.Max10
	}
	return 0
}

func (m *StrengthResult) GetMax11() float64 {
	if m != nil {
		return m.Max11
	}
	return 0
}

type CalcMoment struct {
	Pb       float64           `protobuf:"fixed64,1,opt,name=Pb,json=pb" json:"Pb,omitempty"`
	Pb1      float64           `protobuf:"fixed64,2,opt,name=Pb1,json=pb1" json:"Pb1,omitempty"`
	Pb2      float64           `protobuf:"fixed64,3,opt,name=Pb2,json=pb2" json:"Pb2,omitempty"`
	Pbr      float64           `protobuf:"fixed64,4,opt,name=Pbr,json=pbr" json:"Pbr,omitempty"`
	SigmaB1  float64           `protobuf:"fixed64,5,opt,name=sigmaB1" json:"sigmaB1,omitempty"`
	SigmaB2  float64           `protobuf:"fixed64,6,opt,name=sigmaB2" json:"sigmaB2,omitempty"`
	DSigmaM  float64           `protobuf:"fixed64,7,opt,name=dSigmaM" json:"dSigmaM,omitempty"`
	DSigmaR  float64           `protobuf:"fixed64,8,opt,name=dSigmaR" json:"dSigmaR,omitempty"`
	Q        float64           `protobuf:"fixed64,9,opt,name=q" json:"q,omitempty"`
	QP       float64           `protobuf:"fixed64,10,opt,name=qP" json:"qP,omitempty"`
	Mkp      float64           `protobuf:"fixed64,11,opt,name=Mkp,json=mkp" json:"Mkp,omitempty"`
	Mkp1     float64           `protobuf:"fixed64,12,opt,name=Mkp1,json=mkp1" json:"Mkp1,omitempty"`
	Mrek     float64           `protobuf:"fixed64,13,opt,name=Mrek,json=mrek" json:"Mrek,omitempty"`
	Qrek     float64           `protobuf:"fixed64,14,opt,name=Qrek,json=qrek" json:"Qrek,omitempty"`
	Mmax     float64           `protobuf:"fixed64,15,opt,name=Mmax,json=mmax" json:"Mmax,omitempty"`
	Qmax     float64           `protobuf:"fixed64,16,opt,name=Qmax,json=qmax" json:"Qmax,omitempty"`
	Strength []*StrengthResult `protobuf:"bytes,17,rep,name=strength" json:"strength,omitempty"`
}

func (m *CalcMoment) Reset()                    { *m = CalcMoment{} }
func (m *CalcMoment) String() string            { return proto.CompactTextString(m) }
func (*CalcMoment) ProtoMessage()               {}
func (*CalcMoment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *CalcMoment) GetPb() float64 {
	if m != nil {
		return m.Pb
	}
	return 0
}

func (m *CalcMoment) GetPb1() float64 {
	if m != nil {
		return m.Pb1
	}
	return 0
}

func (m *CalcMoment) GetPb2() float64 {
	if m != nil {
		return m.Pb2
	}
	return 0
}

func (m *CalcMoment) GetPbr() float64 {
	if m != nil {
		return m.Pbr
	}
	return 0
}

func (m *CalcMoment) GetSigmaB1() float64 {
	if m != nil {
		return m.SigmaB1
	}
	return 0
}

func (m *CalcMoment) GetSigmaB2() float64 {
	if m != nil {
		return m.SigmaB2
	}
	return 0
}

func (m *CalcMoment) GetDSigmaM() float64 {
	if m != nil {
		return m.DSigmaM
	}
	return 0
}

func (m *CalcMoment) GetDSigmaR() float64 {
	if m != nil {
		return m.DSigmaR
	}
	return 0
}

func (m *CalcMoment) GetQ() float64 {
	if m != nil {
		return m.Q
	}
	return 0
}

func (m *CalcMoment) GetQP() float64 {
	if m != nil {
		return m.QP
	}
	return 0
}

func (m *CalcMoment) GetMkp() float64 {
	if m != nil {
		return m.Mkp
	}
	return 0
}

func (m *CalcMoment) GetMkp1() float64 {
	if m != nil {
		return m.Mkp1
	}
	return 0
}

func (m *CalcMoment) GetMrek() float64 {
	if m != nil {
		return m.Mrek
	}
	return 0
}

func (m *CalcMoment) GetQrek() float64 {
	if m != nil {
		return m.Qrek
	}
	return 0
}

func (m *CalcMoment) GetMmax() float64 {
	if m != nil {
		return m.Mmax
	}
	return 0
}

func (m *CalcMoment) GetQmax() float64 {
	if m != nil {
		return m.Qmax
	}
	return 0
}

func (m *CalcMoment) GetStrength() []*StrengthResult {
	if m != nil {
		return m.Strength
	}
	return nil
}

type CalculatedFlange struct {
	B0       float64     `protobuf:"fixed64,1,opt,name=b0" json:"b0,omitempty"`
	Dsp      float64     `protobuf:"fixed64,2,opt,name=Dsp,json=dsp" json:"Dsp,omitempty"`
	Po       float64     `protobuf:"fixed64,3,opt,name=Po,json=po" json:"Po,omitempty"`
	Rp       float64     `protobuf:"fixed64,4,opt,name=Rp,json=rp" json:"Rp,omitempty"`
	A        float64     `protobuf:"fixed64,5,opt,name=A,json=a" json:"A,omitempty"`
	Qd       float64     `protobuf:"fixed64,6,opt,name=Qd,json=qd" json:"Qd,omitempty"`
	Qfm      float64     `protobuf:"fixed64,7,opt,name=Qfm,json=qfm" json:"Qfm,omitempty"`
	Qt       float64     `protobuf:"fixed64,8,opt,name=Qt,json=qt" json:"Qt,omitempty"`
	Alpha    float64     `protobuf:"fixed64,9,opt,name=alpha" json:"alpha,omitempty"`
	AlphaM   float64     `protobuf:"fixed64,10,opt,name=alphaM" json:"alphaM,omitempty"`
	Strength *CalcMoment `protobuf:"bytes,11,opt,name=strength" json:"strength,omitempty"`
	Basis    *CalcMoment `protobuf:"bytes,12,opt,name=basis" json:"basis,omitempty"`
}

func (m *CalculatedFlange) Reset()                    { *m = CalculatedFlange{} }
func (m *CalculatedFlange) String() string            { return proto.CompactTextString(m) }
func (*CalculatedFlange) ProtoMessage()               {}
func (*CalculatedFlange) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *CalculatedFlange) GetB0() float64 {
	if m != nil {
		return m.B0
	}
	return 0
}

func (m *CalculatedFlange) GetDsp() float64 {
	if m != nil {
		return m.Dsp
	}
	return 0
}

func (m *CalculatedFlange) GetPo() float64 {
	if m != nil {
		return m.Po
	}
	return 0
}

func (m *CalculatedFlange) GetRp() float64 {
	if m != nil {
		return m.Rp
	}
	return 0
}

func (m *CalculatedFlange) GetA() float64 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *CalculatedFlange) GetQd() float64 {
	if m != nil {
		return m.Qd
	}
	return 0
}

func (m *CalculatedFlange) GetQfm() float64 {
	if m != nil {
		return m.Qfm
	}
	return 0
}

func (m *CalculatedFlange) GetQt() float64 {
	if m != nil {
		return m.Qt
	}
	return 0
}

func (m *CalculatedFlange) GetAlpha() float64 {
	if m != nil {
		return m.Alpha
	}
	return 0
}

func (m *CalculatedFlange) GetAlphaM() float64 {
	if m != nil {
		return m.AlphaM
	}
	return 0
}

func (m *CalculatedFlange) GetStrength() *CalcMoment {
	if m != nil {
		return m.Strength
	}
	return nil
}

func (m *CalculatedFlange) GetBasis() *CalcMoment {
	if m != nil {
		return m.Basis
	}
	return nil
}

type CalcFormulas struct {
	B0      string `protobuf:"bytes,1,opt,name=b0" json:"b0,omitempty"`
	Dsp     string `protobuf:"bytes,2,opt,name=Dsp,json=dsp" json:"Dsp,omitempty"`
	Po      string `protobuf:"bytes,3,opt,name=Po,json=po" json:"Po,omitempty"`
	Rp      string `protobuf:"bytes,4,opt,name=Rp,json=rp" json:"Rp,omitempty"`
	A       string `protobuf:"bytes,5,opt,name=A,json=a" json:"A,omitempty"`
	Qd      string `protobuf:"bytes,6,opt,name=Qd,json=qd" json:"Qd,omitempty"`
	Qfm     string `protobuf:"bytes,7,opt,name=Qfm,json=qfm" json:"Qfm,omitempty"`
	Qt      string `protobuf:"bytes,8,opt,name=Qt,json=qt" json:"Qt,omitempty"`
	Pb      string `protobuf:"bytes,9,opt,name=Pb,json=pb" json:"Pb,omitempty"`
	Alpha   string `protobuf:"bytes,10,opt,name=alpha" json:"alpha,omitempty"`
	AlphaM  string `protobuf:"bytes,11,opt,name=alphaM" json:"alphaM,omitempty"`
	Pb1     string `protobuf:"bytes,12,opt,name=Pb1,json=pb1" json:"Pb1,omitempty"`
	Pb2     string `protobuf:"bytes,13,opt,name=Pb2,json=pb2" json:"Pb2,omitempty"`
	Pbr     string `protobuf:"bytes,14,opt,name=Pbr,json=pbr" json:"Pbr,omitempty"`
	SigmaB1 string `protobuf:"bytes,15,opt,name=sigmaB1" json:"sigmaB1,omitempty"`
	SigmaB2 string `protobuf:"bytes,16,opt,name=sigmaB2" json:"sigmaB2,omitempty"`
	DSigmaM string `protobuf:"bytes,17,opt,name=dSigmaM" json:"dSigmaM,omitempty"`
	DSigmaR string `protobuf:"bytes,18,opt,name=dSigmaR" json:"dSigmaR,omitempty"`
	Q       string `protobuf:"bytes,19,opt,name=q" json:"q,omitempty"`
	QP      string `protobuf:"bytes,20,opt,name=qP" json:"qP,omitempty"`
	Mkp     string `protobuf:"bytes,21,opt,name=Mkp,json=mkp" json:"Mkp,omitempty"`
	Mkp1    string `protobuf:"bytes,22,opt,name=Mkp1,json=mkp1" json:"Mkp1,omitempty"`
	Mrek    string `protobuf:"bytes,23,opt,name=Mrek,json=mrek" json:"Mrek,omitempty"`
	Qrek    string `protobuf:"bytes,24,opt,name=Qrek,json=qrek" json:"Qrek,omitempty"`
	Mmax    string `protobuf:"bytes,25,opt,name=Mmax,json=mmax" json:"Mmax,omitempty"`
	Qmax    string `protobuf:"bytes,26,opt,name=Qmax,json=qmax" json:"Qmax,omitempty"`
}

func (m *CalcFormulas) Reset()                    { *m = CalcFormulas{} }
func (m *CalcFormulas) String() string            { return proto.CompactTextString(m) }
func (*CalcFormulas) ProtoMessage()               {}
func (*CalcFormulas) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *CalcFormulas) GetB0() string {
	if m != nil {
		return m.B0
	}
	return ""
}

func (m *CalcFormulas) GetDsp() string {
	if m != nil {
		return m.Dsp
	}
	return ""
}

func (m *CalcFormulas) GetPo() string {
	if m != nil {
		return m.Po
	}
	return ""
}

func (m *CalcFormulas) GetRp() string {
	if m != nil {
		return m.Rp
	}
	return ""
}

func (m *CalcFormulas) GetA() string {
	if m != nil {
		return m.A
	}
	return ""
}

func (m *CalcFormulas) GetQd() string {
	if m != nil {
		return m.Qd
	}
	return ""
}

func (m *CalcFormulas) GetQfm() string {
	if m != nil {
		return m.Qfm
	}
	return ""
}

func (m *CalcFormulas) GetQt() string {
	if m != nil {
		return m.Qt
	}
	return ""
}

func (m *CalcFormulas) GetPb() string {
	if m != nil {
		return m.Pb
	}
	return ""
}

func (m *CalcFormulas) GetAlpha() string {
	if m != nil {
		return m.Alpha
	}
	return ""
}

func (m *CalcFormulas) GetAlphaM() string {
	if m != nil {
		return m.AlphaM
	}
	return ""
}

func (m *CalcFormulas) GetPb1() string {
	if m != nil {
		return m.Pb1
	}
	return ""
}

func (m *CalcFormulas) GetPb2() string {
	if m != nil {
		return m.Pb2
	}
	return ""
}

func (m *CalcFormulas) GetPbr() string {
	if m != nil {
		return m.Pbr
	}
	return ""
}

func (m *CalcFormulas) GetSigmaB1() string {
	if m != nil {
		return m.SigmaB1
	}
	return ""
}

func (m *CalcFormulas) GetSigmaB2() string {
	if m != nil {
		return m.SigmaB2
	}
	return ""
}

func (m *CalcFormulas) GetDSigmaM() string {
	if m != nil {
		return m.DSigmaM
	}
	return ""
}

func (m *CalcFormulas) GetDSigmaR() string {
	if m != nil {
		return m.DSigmaR
	}
	return ""
}

func (m *CalcFormulas) GetQ() string {
	if m != nil {
		return m.Q
	}
	return ""
}

func (m *CalcFormulas) GetQP() string {
	if m != nil {
		return m.QP
	}
	return ""
}

func (m *CalcFormulas) GetMkp() string {
	if m != nil {
		return m.Mkp
	}
	return ""
}

func (m *CalcFormulas) GetMkp1() string {
	if m != nil {
		return m.Mkp1
	}
	return ""
}

func (m *CalcFormulas) GetMrek() string {
	if m != nil {
		return m.Mrek
	}
	return ""
}

func (m *CalcFormulas) GetQrek() string {
	if m != nil {
		return m.Qrek
	}
	return ""
}

func (m *CalcFormulas) GetMmax() string {
	if m != nil {
		return m.Mmax
	}
	return ""
}

func (m *CalcFormulas) GetQmax() string {
	if m != nil {
		return m.Qmax
	}
	return ""
}

type FlangeResponse struct {
	IsSameFlange bool              `protobuf:"varint,1,opt,name=isSameFlange" json:"isSameFlange,omitempty"`
	Flanges      []*FlangeResult   `protobuf:"bytes,2,rep,name=flanges" json:"flanges,omitempty"`
	Bolt         *BoltResult       `protobuf:"bytes,3,opt,name=bolt" json:"bolt,omitempty"`
	Gasket       *GasketResult     `protobuf:"bytes,4,opt,name=gasket" json:"gasket,omitempty"`
	Embed        *EmbedResult      `protobuf:"bytes,5,opt,name=embed" json:"embed,omitempty"`
	Calc         *CalculatedFlange `protobuf:"bytes,6,opt,name=calc" json:"calc,omitempty"`
	Formulas     *CalcFormulas     `protobuf:"bytes,7,opt,name=formulas" json:"formulas,omitempty"`
}

func (m *FlangeResponse) Reset()                    { *m = FlangeResponse{} }
func (m *FlangeResponse) String() string            { return proto.CompactTextString(m) }
func (*FlangeResponse) ProtoMessage()               {}
func (*FlangeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *FlangeResponse) GetIsSameFlange() bool {
	if m != nil {
		return m.IsSameFlange
	}
	return false
}

func (m *FlangeResponse) GetFlanges() []*FlangeResult {
	if m != nil {
		return m.Flanges
	}
	return nil
}

func (m *FlangeResponse) GetBolt() *BoltResult {
	if m != nil {
		return m.Bolt
	}
	return nil
}

func (m *FlangeResponse) GetGasket() *GasketResult {
	if m != nil {
		return m.Gasket
	}
	return nil
}

func (m *FlangeResponse) GetEmbed() *EmbedResult {
	if m != nil {
		return m.Embed
	}
	return nil
}

func (m *FlangeResponse) GetCalc() *CalculatedFlange {
	if m != nil {
		return m.Calc
	}
	return nil
}

func (m *FlangeResponse) GetFormulas() *CalcFormulas {
	if m != nil {
		return m.Formulas
	}
	return nil
}

func init() {
	proto.RegisterType((*PingRequest)(nil), "moment_proto.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "moment_proto.PingResponse")
	proto.RegisterType((*Gasket)(nil), "moment_proto.Gasket")
	proto.RegisterType((*FlangeData)(nil), "moment_proto.FlangeData")
	proto.RegisterType((*BoltData)(nil), "moment_proto.BoltData")
	proto.RegisterType((*GasketData)(nil), "moment_proto.GasketData")
	proto.RegisterType((*EmbedData)(nil), "moment_proto.EmbedData")
	proto.RegisterType((*FlangeRequest)(nil), "moment_proto.FlangeRequest")
	proto.RegisterType((*FlangeResult)(nil), "moment_proto.FlangeResult")
	proto.RegisterType((*BoltResult)(nil), "moment_proto.BoltResult")
	proto.RegisterType((*GasketResult)(nil), "moment_proto.GasketResult")
	proto.RegisterType((*EmbedResult)(nil), "moment_proto.EmbedResult")
	proto.RegisterType((*StrengthResult)(nil), "moment_proto.StrengthResult")
	proto.RegisterType((*CalcMoment)(nil), "moment_proto.CalcMoment")
	proto.RegisterType((*CalculatedFlange)(nil), "moment_proto.CalculatedFlange")
	proto.RegisterType((*CalcFormulas)(nil), "moment_proto.CalcFormulas")
	proto.RegisterType((*FlangeResponse)(nil), "moment_proto.FlangeResponse")
	proto.RegisterEnum("moment_proto.FlangeData_Type", FlangeData_Type_name, FlangeData_Type_value)
	proto.RegisterEnum("moment_proto.FlangeRequest_Flanges", FlangeRequest_Flanges_name, FlangeRequest_Flanges_value)
	proto.RegisterEnum("moment_proto.FlangeRequest_Type", FlangeRequest_Type_name, FlangeRequest_Type_value)
	proto.RegisterEnum("moment_proto.FlangeRequest_Condition", FlangeRequest_Condition_name, FlangeRequest_Condition_value)
	proto.RegisterEnum("moment_proto.FlangeRequest_Calcutation", FlangeRequest_Calcutation_name, FlangeRequest_Calcutation_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PingService service

type PingServiceClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type pingServiceClient struct {
	cc *grpc.ClientConn
}

func NewPingServiceClient(cc *grpc.ClientConn) PingServiceClient {
	return &pingServiceClient{cc}
}

func (c *pingServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := grpc.Invoke(ctx, "/moment_proto.PingService/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PingService service

type PingServiceServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
}

func RegisterPingServiceServer(s *grpc.Server, srv PingServiceServer) {
	s.RegisterService(&_PingService_serviceDesc, srv)
}

func _PingService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moment_proto.PingService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "moment_proto.PingService",
	HandlerType: (*PingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _PingService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/moment.proto",
}

// Client API for FlangeService service

type FlangeServiceClient interface {
	CalculateFlange(ctx context.Context, in *FlangeRequest, opts ...grpc.CallOption) (*FlangeResponse, error)
}

type flangeServiceClient struct {
	cc *grpc.ClientConn
}

func NewFlangeServiceClient(cc *grpc.ClientConn) FlangeServiceClient {
	return &flangeServiceClient{cc}
}

func (c *flangeServiceClient) CalculateFlange(ctx context.Context, in *FlangeRequest, opts ...grpc.CallOption) (*FlangeResponse, error) {
	out := new(FlangeResponse)
	err := grpc.Invoke(ctx, "/moment_proto.FlangeService/CalculateFlange", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FlangeService service

type FlangeServiceServer interface {
	CalculateFlange(context.Context, *FlangeRequest) (*FlangeResponse, error)
}

func RegisterFlangeServiceServer(s *grpc.Server, srv FlangeServiceServer) {
	s.RegisterService(&_FlangeService_serviceDesc, srv)
}

func _FlangeService_CalculateFlange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlangeServiceServer).CalculateFlange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moment_proto.FlangeService/CalculateFlange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlangeServiceServer).CalculateFlange(ctx, req.(*FlangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FlangeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "moment_proto.FlangeService",
	HandlerType: (*FlangeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateFlange",
			Handler:    _FlangeService_CalculateFlange_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/moment.proto",
}

func init() { proto.RegisterFile("proto/moment.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 2036 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0x4f, 0x73, 0xdb, 0xc6,
	0xf9, 0x36, 0x40, 0x52, 0x22, 0x5f, 0x52, 0x14, 0xb5, 0x56, 0x6c, 0x58, 0x71, 0xfc, 0xd3, 0x0f,
	0x49, 0x5c, 0x1d, 0x52, 0x99, 0xa4, 0x15, 0xc5, 0x69, 0x27, 0x07, 0xdb, 0xa9, 0x3a, 0x1a, 0x87,
	0xad, 0x0c, 0x7b, 0xa6, 0x33, 0x9d, 0xe9, 0x78, 0x40, 0x62, 0x29, 0x61, 0x88, 0x7f, 0x04, 0x40,
	0x47, 0xca, 0xa9, 0x87, 0x1c, 0x7a, 0x6c, 0xef, 0xfd, 0x00, 0xfd, 0x52, 0xed, 0xbd, 0xdf, 0xa2,
	0xb3, 0xef, 0xbe, 0xbb, 0x58, 0xd0, 0xb4, 0x0e, 0x9d, 0xe9, 0x89, 0x7c, 0x9e, 0x7d, 0x77, 0xb1,
	0xfb, 0xee, 0xfb, 0x3c, 0xd8, 0x05, 0xb0, 0x2c, 0x4f, 0xcb, 0xf4, 0x49, 0x9c, 0xc6, 0x3c, 0x29,
	0x8f, 0x11, 0xb0, 0x9e, 0x44, 0xef, 0x10, 0xb9, 0x3b, 0xd0, 0xbd, 0x08, 0x93, 0x4b, 0x8f, 0x2f,
	0x57, 0xbc, 0x28, 0x5d, 0x17, 0x7a, 0x12, 0x16, 0x59, 0x9a, 0x14, 0x9c, 0x31, 0x68, 0x66, 0x61,
	0x72, 0xe9, 0x58, 0x87, 0xd6, 0x51, 0xc7, 0xc3, 0xff, 0x6e, 0x1b, 0xb6, 0x7e, 0xeb, 0x17, 0x0b,
	0x5e, 0xba, 0xff, 0xb4, 0x00, 0xce, 0x22, 0x3f, 0xb9, 0xe4, 0xdf, 0xfb, 0xa5, 0xcf, 0x46, 0xd0,
	0x2c, 0x6f, 0x32, 0x8e, 0xc1, 0xfd, 0xf1, 0x67, 0xc7, 0xe6, 0x83, 0x8e, 0xab, 0xb8, 0xe3, 0xb7,
	0x37, 0x19, 0xf7, 0x30, 0x94, 0x3d, 0x02, 0x28, 0x4a, 0x3f, 0x09, 0xfc, 0xbc, 0x3c, 0x0f, 0x1c,
	0x1b, 0x9f, 0x62, 0x30, 0xec, 0x1e, 0x6c, 0xc5, 0x7e, 0xbe, 0x38, 0x0f, 0x9c, 0x06, 0xb6, 0x11,
	0x62, 0x7d, 0xb0, 0x83, 0x1b, 0xa7, 0x79, 0x68, 0x1d, 0xb5, 0x3c, 0x3b, 0xb8, 0x11, 0x38, 0xbb,
	0x71, 0x5a, 0x87, 0xd6, 0x91, 0xe5, 0xd9, 0xd9, 0x0d, 0x7b, 0x08, 0x9d, 0x59, 0x9a, 0xe7, 0x69,
	0x11, 0xa6, 0x89, 0xb3, 0x85, 0x74, 0x45, 0xb8, 0x8f, 0xa1, 0x29, 0xe6, 0xc0, 0x00, 0xb6, 0x7e,
	0xe4, 0x51, 0xc0, 0x83, 0xc1, 0x1d, 0xd6, 0x86, 0xe6, 0x3c, 0xf2, 0xcb, 0x81, 0x85, 0xff, 0x72,
	0xce, 0x07, 0xb6, 0xeb, 0x42, 0xfb, 0x45, 0x1a, 0x95, 0xb8, 0xb8, 0x6a, 0x26, 0x96, 0x39, 0x13,
	0xf7, 0x67, 0x0b, 0x40, 0xa6, 0x03, 0xc3, 0x0e, 0xa0, 0x7d, 0x89, 0x48, 0x07, 0x6a, 0xcc, 0xf6,
	0xa1, 0xc5, 0x93, 0xf7, 0x7a, 0x9d, 0x12, 0x88, 0xa9, 0x96, 0x57, 0xe1, 0x6c, 0x91, 0xf0, 0xa2,
	0xc0, 0x55, 0x5a, 0x5e, 0x45, 0xb0, 0xbb, 0xd0, 0x0a, 0xde, 0xa5, 0xab, 0x12, 0xd7, 0x6a, 0x79,
	0xcd, 0xe0, 0xf7, 0xab, 0x92, 0xed, 0x41, 0x33, 0x78, 0x17, 0x26, 0xb4, 0xde, 0x46, 0x70, 0x9e,
	0xb8, 0xcf, 0xa1, 0xf3, 0x9b, 0x78, 0xca, 0x83, 0xdb, 0xe6, 0x5a, 0x7f, 0x94, 0xbd, 0xf6, 0x28,
	0xf7, 0xef, 0xdb, 0xb0, 0x23, 0x77, 0x89, 0xaa, 0x41, 0x2c, 0x26, 0xcb, 0x79, 0x51, 0xac, 0x72,
	0xb9, 0xa9, 0x96, 0xa7, 0xb1, 0xd8, 0x39, 0xff, 0x3a, 0xf4, 0xa3, 0xb3, 0x34, 0x9f, 0x71, 0x1c,
	0xac, 0xe5, 0x19, 0x0c, 0xfb, 0x02, 0x76, 0xa6, 0x3c, 0x09, 0xc2, 0xe4, 0x72, 0x82, 0x65, 0x80,
	0x4b, 0x6b, 0x79, 0x75, 0x52, 0xd4, 0x57, 0xc9, 0xe3, 0x4c, 0xad, 0x4e, 0xfc, 0x17, 0xb3, 0x0f,
	0x8b, 0x3f, 0xa4, 0xf9, 0x02, 0xd7, 0xd7, 0xf6, 0x08, 0xb1, 0xef, 0x60, 0x7b, 0x8e, 0xd3, 0x2b,
	0x70, 0x47, 0xfb, 0xe3, 0xcf, 0x37, 0x55, 0x18, 0xcd, 0x9d, 0x50, 0xe1, 0xa9, 0x3e, 0xcc, 0x85,
	0x5e, 0x58, 0xbc, 0xf1, 0x63, 0x2e, 0x5b, 0x9c, 0x6d, 0x1c, 0xbc, 0xc6, 0x89, 0x45, 0x85, 0x05,
	0xe6, 0x31, 0xe0, 0x81, 0xd3, 0xc6, 0x08, 0x83, 0x61, 0x27, 0x54, 0xe1, 0x1d, 0x7c, 0xfe, 0xe1,
	0x6d, 0xcf, 0x37, 0x8a, 0xfc, 0xa5, 0x28, 0xc6, 0x24, 0x08, 0x4b, 0x51, 0x8c, 0x80, 0x5d, 0xbf,
	0xbc, 0xad, 0xeb, 0x4b, 0x15, 0xec, 0x55, 0xfd, 0xd8, 0x39, 0x74, 0x67, 0x7e, 0x34, 0x5b, 0x45,
	0x3e, 0x0e, 0xd3, 0xc5, 0x61, 0x7e, 0x71, 0xeb, 0x30, 0x22, 0xbc, 0xc4, 0x70, 0xcf, 0xec, 0xcb,
	0x7e, 0x05, 0x5d, 0x4a, 0x8a, 0xa8, 0x16, 0xa7, 0x77, 0xd8, 0x38, 0xea, 0x8e, 0x9d, 0x8f, 0xc9,
	0xd5, 0x33, 0x83, 0xd9, 0x57, 0xd0, 0x9a, 0xa6, 0x51, 0x59, 0x38, 0x3b, 0x87, 0xd6, 0x51, 0x77,
	0x7c, 0xaf, 0xde, 0x4b, 0xa9, 0xc5, 0x93, 0x41, 0x6c, 0x08, 0x5b, 0xb2, 0xfa, 0x9d, 0x3e, 0x86,
	0xaf, 0x3d, 0xa4, 0xd2, 0x8d, 0x47, 0x71, 0xec, 0x97, 0xd0, 0xe2, 0x22, 0xdb, 0xce, 0x2e, 0x76,
	0xb8, 0x5f, 0xef, 0xa0, 0x4b, 0xdc, 0x93, 0x51, 0xec, 0x31, 0xf4, 0xc3, 0xe2, 0x77, 0x9c, 0x07,
	0x67, 0x69, 0x1e, 0xaf, 0x22, 0xbf, 0x70, 0x06, 0xb8, 0x69, 0x6b, 0xac, 0x7b, 0x0a, 0xdb, 0x54,
	0x10, 0xac, 0x07, 0xed, 0xb0, 0x48, 0x23, 0xbf, 0x44, 0xd9, 0xef, 0x42, 0x37, 0x49, 0x93, 0x73,
	0x45, 0x58, 0xa2, 0x39, 0xf6, 0x93, 0x95, 0x1f, 0x45, 0x37, 0x03, 0xdb, 0x7d, 0x40, 0x4e, 0xd1,
	0x86, 0xa6, 0x58, 0xd1, 0xe0, 0x0e, 0xdb, 0x86, 0x46, 0x16, 0x26, 0x03, 0xcb, 0x3d, 0x83, 0x8e,
	0xde, 0x28, 0xc6, 0xa0, 0xbf, 0x4a, 0x66, 0x69, 0x52, 0xe6, 0x69, 0x14, 0xf9, 0xd3, 0x88, 0x0f,
	0xee, 0xb0, 0x01, 0xf4, 0x6a, 0x8c, 0xc5, 0xee, 0xc2, 0xae, 0xc9, 0x5c, 0x84, 0xc9, 0xc0, 0x76,
	0x1f, 0x43, 0xd7, 0xd8, 0x29, 0xd6, 0x81, 0xd6, 0xd4, 0x2f, 0xc2, 0x62, 0x70, 0x47, 0x4c, 0xa5,
	0x28, 0x73, 0x9e, 0x5c, 0x96, 0x57, 0x03, 0xcb, 0xfd, 0x6b, 0x0b, 0x7a, 0x6a, 0x83, 0x8b, 0x55,
	0x84, 0xda, 0x11, 0x6e, 0x40, 0xca, 0x94, 0xce, 0xd0, 0x03, 0x2b, 0x20, 0x65, 0x5b, 0xd2, 0x25,
	0x17, 0xe4, 0x29, 0x76, 0xb0, 0x60, 0x03, 0x68, 0x04, 0xc9, 0x82, 0xc4, 0x26, 0xfe, 0x62, 0x44,
	0xa1, 0x7c, 0x33, 0x10, 0xc9, 0xb1, 0xae, 0xc8, 0x2f, 0xad, 0x2b, 0xd1, 0x7a, 0xb5, 0x40, 0xa1,
	0x58, 0x9e, 0x7d, 0x85, 0xd1, 0xc5, 0x10, 0x65, 0x61, 0x79, 0x76, 0x31, 0x44, 0x3c, 0x42, 0x31,
	0x08, 0x3c, 0x12, 0xbd, 0x23, 0x2c, 0x70, 0xcb, 0xb3, 0x22, 0x1c, 0xfb, 0x14, 0x0b, 0x55, 0x8c,
	0x7d, 0x2a, 0x5a, 0x67, 0x4e, 0x4f, 0xb6, 0xce, 0x44, 0x6b, 0x39, 0xc7, 0x2a, 0xb2, 0x3c, 0xbb,
	0x9c, 0x23, 0x5e, 0x60, 0x99, 0x08, 0xbc, 0x10, 0x2e, 0xe0, 0x47, 0xd9, 0x95, 0xff, 0x0a, 0x2b,
	0xc1, 0xf2, 0x08, 0x09, 0x19, 0xf3, 0xac, 0x08, 0xa3, 0x34, 0x79, 0xf5, 0xbc, 0x1c, 0x0f, 0x71,
	0xbf, 0x2d, 0xaf, 0xc6, 0x09, 0xdf, 0x52, 0xd8, 0xd9, 0x93, 0xbe, 0xa5, 0x30, 0xbe, 0x71, 0xc2,
	0xcb, 0xd8, 0x97, 0xbd, 0x19, 0xb6, 0x1a, 0x8c, 0x78, 0xae, 0x44, 0xce, 0x5d, 0xf9, 0x5c, 0x89,
	0xf4, 0x7c, 0xce, 0x9c, 0x7d, 0x63, 0x3e, 0x67, 0xec, 0x10, 0xba, 0x34, 0x36, 0x0e, 0xf8, 0x09,
	0x36, 0x9a, 0x14, 0x73, 0x60, 0x9b, 0xa0, 0x73, 0x0f, 0x5b, 0x15, 0x14, 0x7e, 0x8c, 0xa3, 0x63,
	0xcf, 0xfb, 0xd2, 0x8f, 0x35, 0x21, 0x5e, 0x17, 0x08, 0x1c, 0x07, 0x5b, 0x24, 0xd0, 0xf3, 0x9b,
	0x38, 0x0f, 0x8c, 0xf9, 0x4d, 0xf4, 0xba, 0x26, 0x38, 0xd8, 0x81, 0xb1, 0xae, 0x49, 0x6d, 0x5d,
	0x9e, 0xf3, 0xa9, 0xd1, 0xcf, 0xd3, 0xfd, 0x3c, 0xec, 0xf7, 0xd0, 0xe8, 0xe7, 0xa9, 0x5c, 0xc6,
	0x7e, 0xc9, 0xf3, 0xd0, 0x8f, 0x9c, 0xcf, 0xe4, 0x0b, 0x4d, 0x61, 0xf7, 0x67, 0x1b, 0x40, 0x48,
	0x9e, 0x0a, 0xf2, 0x00, 0xda, 0x41, 0xe8, 0xc7, 0xbc, 0xe4, 0x39, 0x16, 0x65, 0xcb, 0xd3, 0x58,
	0x14, 0xab, 0x9f, 0x73, 0x9f, 0x6a, 0x13, 0xff, 0x8b, 0x05, 0xce, 0xd2, 0x95, 0x7e, 0x35, 0x48,
	0x20, 0x26, 0x1a, 0xf1, 0xe4, 0xf2, 0x4a, 0xbd, 0xf2, 0x08, 0xe9, 0x57, 0x45, 0xcb, 0x78, 0x55,
	0xec, 0x43, 0x0b, 0xb7, 0x81, 0x4a, 0x56, 0x82, 0xf5, 0x2d, 0xd9, 0xbe, 0x75, 0x4b, 0xda, 0xb7,
	0x6c, 0x49, 0xe7, 0xa3, 0x5b, 0x02, 0xc6, 0x96, 0xb8, 0x7f, 0xb3, 0xa1, 0x27, 0xad, 0xac, 0x4a,
	0xc4, 0xff, 0xfe, 0x10, 0xb0, 0x0f, 0xad, 0x1f, 0xc3, 0xa0, 0xbc, 0xa2, 0x84, 0x48, 0x20, 0x44,
	0x16, 0x2b, 0x01, 0xc7, 0x78, 0x7c, 0xcb, 0x79, 0x41, 0x29, 0xc0, 0xff, 0x22, 0x3b, 0xb3, 0x34,
	0xc6, 0xf7, 0x78, 0xa8, 0xd7, 0x6f, 0x52, 0x66, 0x76, 0x3a, 0xf5, 0xec, 0x1c, 0xc1, 0x6e, 0xc6,
	0xf3, 0x38, 0x2c, 0x8a, 0x50, 0xf8, 0x97, 0x18, 0x5a, 0x66, 0x62, 0x9d, 0x76, 0x63, 0xe8, 0xa2,
	0x59, 0x53, 0x46, 0xfe, 0xab, 0x13, 0x09, 0x6d, 0xef, 0xdc, 0xa7, 0x8c, 0x48, 0xb0, 0xe9, 0xcc,
	0xe0, 0xfe, 0x6b, 0x0b, 0xfa, 0x6f, 0xc8, 0x2b, 0xe9, 0x91, 0x03, 0x68, 0x4c, 0x16, 0x19, 0xb9,
	0x63, 0x23, 0x5e, 0x64, 0xa2, 0xe3, 0x64, 0x91, 0x8d, 0x54, 0x0d, 0xc6, 0x8b, 0x6c, 0x24, 0x6c,
	0xe7, 0xe5, 0x5c, 0x59, 0xe4, 0x6c, 0x2e, 0x7a, 0x7d, 0xff, 0xd3, 0x7b, 0x6d, 0x91, 0x3f, 0xbd,
	0x17, 0x11, 0x93, 0x89, 0xb2, 0xc8, 0x78, 0x82, 0xe3, 0x4e, 0x16, 0x94, 0xe3, 0x46, 0x3c, 0x41,
	0x5b, 0x9d, 0x64, 0xca, 0x27, 0x1b, 0x71, 0x86, 0x46, 0x39, 0xc9, 0x94, 0x51, 0xc6, 0x99, 0xc8,
	0xa8, 0x94, 0xa2, 0x72, 0x4b, 0x05, 0xab, 0x96, 0x21, 0x65, 0x52, 0x41, 0x2d, 0xd8, 0xb7, 0x64,
	0xa1, 0x84, 0x0c, 0x21, 0xf7, 0x6a, 0x42, 0x56, 0x23, 0xbd, 0xcd, 0xc8, 0x55, 0x15, 0xd4, 0x2d,
	0x5e, 0x46, 0xfe, 0xaa, 0xa0, 0x61, 0x76, 0xbb, 0x35, 0xb3, 0x53, 0x3d, 0x2e, 0x46, 0xe4, 0xaf,
	0x0a, 0x56, 0x2d, 0x43, 0x72, 0x56, 0x05, 0xab, 0x95, 0x64, 0xe4, 0xaa, 0x0a, 0x0a, 0x39, 0xd0,
	0xdf, 0x98, 0x4c, 0x55, 0x63, 0xa3, 0x6d, 0x48, 0xc6, 0xaa, 0xb1, 0xd6, 0xe2, 0x24, 0x8b, 0x95,
	0xb1, 0x56, 0x44, 0xd5, 0x33, 0xcd, 0xc8, 0x57, 0x35, 0xd6, 0x73, 0x79, 0x95, 0x91, 0xad, 0x2a,
	0x28, 0x8b, 0xa7, 0x54, 0x9e, 0x8a, 0xff, 0x45, 0x99, 0x05, 0x6f, 0x05, 0x29, 0x1d, 0x55, 0x02,
	0x91, 0x1b, 0xfc, 0xf3, 0x8a, 0xcc, 0x94, 0x90, 0x88, 0x2e, 0x91, 0x96, 0x3e, 0x2a, 0x01, 0xd6,
	0x96, 0x7f, 0x3d, 0x22, 0x03, 0x6d, 0xc6, 0xfe, 0xf5, 0x88, 0xb8, 0x31, 0xda, 0xa6, 0xe4, 0xc6,
	0xc4, 0x3d, 0x75, 0x1e, 0x69, 0xee, 0x29, 0x71, 0x27, 0xce, 0xff, 0x69, 0xee, 0x84, 0xb8, 0xaf,
	0x9d, 0x43, 0xcd, 0x7d, 0x4d, 0xdc, 0xa9, 0xf3, 0xff, 0x9a, 0x3b, 0x25, 0xee, 0x1b, 0xc7, 0xd5,
	0xdc, 0x37, 0xc4, 0x3d, 0x73, 0x3e, 0xd7, 0xdc, 0x33, 0xe2, 0xbe, 0x75, 0xbe, 0xd0, 0xdc, 0xb7,
	0x62, 0x25, 0x62, 0xce, 0x43, 0xe7, 0x4b, 0xb9, 0x12, 0x31, 0xe9, 0xa1, 0x62, 0x47, 0xce, 0xe3,
	0x8a, 0x1d, 0xb9, 0x7f, 0x69, 0x00, 0x88, 0x63, 0x0a, 0x9d, 0xdb, 0xfb, 0x60, 0x5f, 0x4c, 0x49,
	0x5b, 0x76, 0x36, 0x15, 0x12, 0xb8, 0x98, 0x2a, 0x65, 0x35, 0xb2, 0xe9, 0x48, 0x32, 0x63, 0x52,
	0x56, 0x23, 0x9b, 0x8e, 0x25, 0x93, 0x2b, 0x69, 0x65, 0xd3, 0x5c, 0x6f, 0xd3, 0x8b, 0x11, 0xe9,
	0x4b, 0xc1, 0xaa, 0x65, 0x4c, 0x42, 0x53, 0x50, 0xb4, 0x04, 0x6f, 0xe4, 0x0b, 0x50, 0x0a, 0x4e,
	0xc1, 0xaa, 0xc5, 0x53, 0xa6, 0x4e, 0x50, 0x98, 0xe2, 0x92, 0x84, 0x67, 0x2d, 0xc5, 0xdc, 0x97,
	0x17, 0xa4, 0x36, 0x7b, 0x79, 0xa1, 0x8c, 0xa2, 0xfb, 0xa1, 0x51, 0xf4, 0x0c, 0xa3, 0x10, 0x5c,
	0xce, 0x17, 0xa4, 0xad, 0x66, 0x9c, 0xf3, 0x85, 0xe0, 0x5e, 0x0b, 0x4e, 0xaa, 0xaa, 0xb9, 0x24,
	0x6e, 0x12, 0xfb, 0xd7, 0x24, 0xa8, 0x66, 0x1c, 0xfb, 0xd7, 0x18, 0x27, 0xb8, 0x01, 0xc5, 0x09,
	0xee, 0x59, 0x75, 0xb8, 0x73, 0xf6, 0xf0, 0x04, 0xfe, 0xb0, 0x7e, 0xd6, 0xad, 0xdb, 0x99, 0xa7,
	0xa3, 0xdd, 0x7f, 0xd8, 0x30, 0x78, 0x49, 0xc7, 0x79, 0x1e, 0xd0, 0xcd, 0xa5, 0x0f, 0xf6, 0x74,
	0xa8, 0x36, 0x64, 0x3a, 0x44, 0x1f, 0x2b, 0x32, 0xb5, 0x21, 0x41, 0x91, 0xe1, 0x96, 0xa5, 0xca,
	0xe9, 0xb2, 0x54, 0x60, 0x4f, 0x99, 0xa8, 0x9d, 0x67, 0x22, 0x49, 0xcf, 0x69, 0x1b, 0x2c, 0x5f,
	0xb4, 0xbe, 0x0e, 0x28, 0xf7, 0xf6, 0x32, 0x10, 0xe3, 0xbd, 0x9e, 0xc7, 0xca, 0xe3, 0x96, 0xf3,
	0x18, 0x23, 0x4a, 0xe5, 0x71, 0xcb, 0xb2, 0x7a, 0x17, 0x77, 0xcc, 0x77, 0xb1, 0x3a, 0x36, 0x4d,
	0x28, 0xe1, 0x84, 0xd8, 0x89, 0xb1, 0xfc, 0xee, 0xa6, 0xbb, 0x41, 0x55, 0x6c, 0xd5, 0xd2, 0xd9,
	0x31, 0x1d, 0x8e, 0x71, 0x67, 0x6e, 0xeb, 0x22, 0xc3, 0xdc, 0x3f, 0x37, 0xa1, 0x27, 0x58, 0x75,
	0x0f, 0x30, 0xd2, 0xd4, 0x59, 0x4f, 0x53, 0x67, 0x3d, 0x4d, 0x9d, 0xb5, 0x34, 0x75, 0xea, 0x69,
	0xea, 0xd4, 0xd3, 0xd4, 0x59, 0x4f, 0x53, 0x67, 0x3d, 0x4d, 0x1d, 0x4c, 0x93, 0x54, 0x4e, 0x87,
	0xc6, 0x9f, 0x56, 0x69, 0x03, 0x79, 0x1e, 0x58, 0x4f, 0x5b, 0x57, 0xbe, 0x2f, 0x29, 0x6d, 0xa4,
	0xb3, 0x9e, 0x1c, 0xdf, 0xd0, 0xd9, 0x8e, 0x62, 0xb4, 0xce, 0xfa, 0x8a, 0xa9, 0xe9, 0x6c, 0x17,
	0xd9, 0x4d, 0x3a, 0x1b, 0x98, 0x2d, 0x35, 0x9d, 0xed, 0xc9, 0x96, 0x0d, 0x3a, 0x63, 0x66, 0x0b,
	0xe9, 0xec, 0xae, 0xcc, 0x8d, 0xd2, 0xd9, 0x3e, 0xad, 0x5c, 0xeb, 0xec, 0x13, 0x39, 0x2f, 0x53,
	0x67, 0xf7, 0xe4, 0xd7, 0xa5, 0x9a, 0xce, 0xee, 0x13, 0x67, 0xea, 0xcc, 0x91, 0x5c, 0x4d, 0x67,
	0x0f, 0x28, 0xce, 0xd4, 0xd9, 0x01, 0xc5, 0xc5, 0xfe, 0xb5, 0xfb, 0x6f, 0x1b, 0xfa, 0xfa, 0xda,
	0x24, 0x3f, 0x6a, 0xad, 0x7f, 0x09, 0xb0, 0x36, 0x7c, 0x09, 0x38, 0xa9, 0x3e, 0x36, 0xd8, 0xa8,
	0xce, 0x83, 0xcd, 0x57, 0x6d, 0xd4, 0xa6, 0xfe, 0xc6, 0xf0, 0x95, 0xbc, 0x26, 0x62, 0xf9, 0x7c,
	0x50, 0x9e, 0xd5, 0x49, 0xd9, 0xc3, 0x28, 0x36, 0xd6, 0xb7, 0xe3, 0x26, 0xc6, 0x1f, 0x6c, 0xba,
	0x1d, 0x53, 0x0f, 0x75, 0x3f, 0x7e, 0xa2, 0xee, 0xc7, 0x2d, 0xec, 0xf2, 0x60, 0xc3, 0xfd, 0x98,
	0x7a, 0xd0, 0x0d, 0x79, 0x0c, 0x4d, 0x71, 0xf7, 0xc7, 0x1a, 0xed, 0x8e, 0x1f, 0x7d, 0xa8, 0x18,
	0xd3, 0x46, 0x3c, 0x8c, 0x65, 0xa7, 0xd0, 0x9e, 0xab, 0xfb, 0xf4, 0xf6, 0xa6, 0xa9, 0x99, 0x9a,
	0xf2, 0x74, 0xec, 0xf8, 0x07, 0xf9, 0x31, 0xf1, 0x0d, 0xcf, 0xdf, 0x87, 0x33, 0xce, 0xbe, 0x83,
	0xa6, 0x80, 0x6c, 0x6d, 0x92, 0xc6, 0xf7, 0xc6, 0x83, 0x83, 0x4d, 0x4d, 0x72, 0x9b, 0xc6, 0x7f,
	0x52, 0x9f, 0xa3, 0xd4, 0x78, 0x3f, 0xc0, 0xae, 0x9e, 0x30, 0x6d, 0xd3, 0xa7, 0xb7, 0x7c, 0x00,
	0x39, 0x78, 0xf8, 0x91, 0x2d, 0xc3, 0xe1, 0x5f, 0xec, 0xfd, 0x71, 0xf7, 0xf8, 0xc9, 0xaf, 0xcd,
	0x88, 0xe9, 0x16, 0xfe, 0x3c, 0xfd, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf9, 0x89, 0x0e, 0x67,
	0x37, 0x15, 0x00, 0x00,
}
