basePath: /api/v1
definitions:
  models.DataResponse:
    properties:
      count:
        type: integer
      data: {}
    type: object
  models.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  models.IdResponse:
    properties:
      id:
        type: string
      message:
        type: string
    type: object
  models.StandDTO:
    properties:
      title:
        type: string
    required:
    - title
    type: object
  proto.Flange:
    properties:
      id:
        type: string
      short:
        type: string
      title:
        type: string
    type: object
  proto.Stand:
    properties:
      id:
        type: string
      title:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API Service for Sealur
  title: Sealur
  version: "0.1"
paths:
  /sealur-pro/flanges:
    get:
      consumes:
      - application/json
      description: получение всех стандартов на фланцы
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/models.DataResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/proto.Flange'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Get Flanges
      tags:
      - Sealur Pro -> flanges
    post:
      consumes:
      - application/json
      description: создание стандарта на фланцы
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.IdResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Create Flange
      tags:
      - Sealur Pro -> flanges
  /sealur-pro/flanges/{id}:
    delete:
      consumes:
      - application/json
      description: удаление стандарта на фланцы
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.IdResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Delete Flange
      tags:
      - Sealur Pro -> flanges
    put:
      consumes:
      - application/json
      description: обновление стандарта на фланцы
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.IdResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Update Flange
      tags:
      - Sealur Pro -> flanges
  /sealur-pro/standards:
    get:
      consumes:
      - application/json
      description: получение всех стандартов на прокладки
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/models.DataResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/proto.Stand'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Get Stand
      tags:
      - Sealur Pro -> standards
    post:
      consumes:
      - application/json
      description: создание стандарта на прокладки
      parameters:
      - description: standard info
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.StandDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.IdResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Create Stand
      tags:
      - Sealur Pro -> standards
  /sealur-pro/standards/{id}:
    delete:
      consumes:
      - application/json
      description: удаление стандарта на прокладки
      parameters:
      - description: standard id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.IdResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Delete Stand
      tags:
      - Sealur Pro -> standards
    put:
      consumes:
      - application/json
      description: обновление стандарта на прокладки
      parameters:
      - description: standard info
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.StandDTO'
      - description: standard id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.IdResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Update Stand
      tags:
      - Sealur Pro -> standards
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
