basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: API Service
  title: Sealur Prop
  version: "0.1"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
