version: "3.4"

services:
  redis:
    image: "redis:6.2-alpine"
    volumes:
      - ./.data/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./.data/redis/data:/var/lib/redis
    ports:
      - 6379:6379
