version: '3.4'

services:
  postgres:
    image: postgres:14.1-alpine
    container_name: pro-s-postgres
    volumes:
      - ./create-db.sql:/docker-entrypoint-initdb.d/create-db.sql
      - ./.build/volumes/databases/postgres/data:/var/lib/postgresql/data
    ports:
      - 5436:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
