package repository

const (
	GasketTable           = "gasket"
	EnvTable              = "environment"
	TypeGasketTable       = "type_gasket"
	EnvDataTable          = "env_data"
	GasketDataTable       = "gasket_data"
	MaterialsTable        = "materials"
	VoltageTable          = "voltage"
	ElasticityTable       = "elasticity"
	AlphaTable            = "alpha"
	TypeFlangeTable       = "type_flange"
	StandartsTable        = "standarts"
	BoltsTable            = "bolts"
	FlangeSizeTable       = "flange_size"
	DeviceModTable        = "device_mod"
	TubeCountTable        = "tube_count"
	PressureTable         = "pressure"
	FinningFactorTable    = "finning_factor"
	SectionExecutionTable = "section_execution"
	TubeLenghtTable       = "tube_lenght"
	NumberOfMovesTable    = "number_of_moves"
	NameGasketTable       = "name_gasket"
)
