// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/pro.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	proto/pro.proto

It has these top-level messages:
	GetAllFlangeRequest
	CreateFlangeRequest
	UpdateFlangeRequest
	DeleteFlangeRequest
	Flange
	FlangeResponse
	GetStandsRequest
	CreateStandRequest
	UpdateStandRequest
	DeleteStandRequest
	Stand
	StandResponse
	GetAllAddRequest
	CreateAddRequest
	UpdateAddMatRequest
	UpdateAddModRequest
	UpdateAddTemRequest
	UpdateAddMounRequest
	UpdateAddGrapRequest
	UpdateAddTypeFlRequest
	Additional
	AdditionalResponse
	SuccessResponse
	GetSizesRequest
	CreateSizeRequest
	UpdateSizeRequest
	DeleteSizeRequest
	Size
	SizeResponse
	GetSNPRequest
	CreateSNPRequest
	UpdateSNPRequest
	DeleteSNPRequest
	SNP
	SNPResponse
	IdResponse
	PingRequest
	PingResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

// Flange Service ----------------------------------------------------------------
type GetAllFlangeRequest struct {
}

func (m *GetAllFlangeRequest) Reset()                    { *m = GetAllFlangeRequest{} }
func (m *GetAllFlangeRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetAllFlangeRequest) ProtoMessage()               {}
func (*GetAllFlangeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CreateFlangeRequest struct {
	Title string `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Short string `protobuf:"bytes,2,opt,name=short" json:"short,omitempty"`
}

func (m *CreateFlangeRequest) Reset()                    { *m = CreateFlangeRequest{} }
func (m *CreateFlangeRequest) String() string            { return proto1.CompactTextString(m) }
func (*CreateFlangeRequest) ProtoMessage()               {}
func (*CreateFlangeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateFlangeRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateFlangeRequest) GetShort() string {
	if m != nil {
		return m.Short
	}
	return ""
}

type UpdateFlangeRequest struct {
	Id    string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Title string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Short string `protobuf:"bytes,3,opt,name=short" json:"short,omitempty"`
}

func (m *UpdateFlangeRequest) Reset()                    { *m = UpdateFlangeRequest{} }
func (m *UpdateFlangeRequest) String() string            { return proto1.CompactTextString(m) }
func (*UpdateFlangeRequest) ProtoMessage()               {}
func (*UpdateFlangeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UpdateFlangeRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateFlangeRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdateFlangeRequest) GetShort() string {
	if m != nil {
		return m.Short
	}
	return ""
}

type DeleteFlangeRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteFlangeRequest) Reset()                    { *m = DeleteFlangeRequest{} }
func (m *DeleteFlangeRequest) String() string            { return proto1.CompactTextString(m) }
func (*DeleteFlangeRequest) ProtoMessage()               {}
func (*DeleteFlangeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DeleteFlangeRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Flange struct {
	Id    string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Title string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Short string `protobuf:"bytes,3,opt,name=short" json:"short,omitempty"`
}

func (m *Flange) Reset()                    { *m = Flange{} }
func (m *Flange) String() string            { return proto1.CompactTextString(m) }
func (*Flange) ProtoMessage()               {}
func (*Flange) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Flange) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Flange) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Flange) GetShort() string {
	if m != nil {
		return m.Short
	}
	return ""
}

type FlangeResponse struct {
	Flanges []*Flange `protobuf:"bytes,1,rep,name=flanges" json:"flanges,omitempty"`
}

func (m *FlangeResponse) Reset()                    { *m = FlangeResponse{} }
func (m *FlangeResponse) String() string            { return proto1.CompactTextString(m) }
func (*FlangeResponse) ProtoMessage()               {}
func (*FlangeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *FlangeResponse) GetFlanges() []*Flange {
	if m != nil {
		return m.Flanges
	}
	return nil
}

// Stand Service ----------------------------------------------------------------
type GetStandsRequest struct {
}

func (m *GetStandsRequest) Reset()                    { *m = GetStandsRequest{} }
func (m *GetStandsRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetStandsRequest) ProtoMessage()               {}
func (*GetStandsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type CreateStandRequest struct {
	Title string `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
}

func (m *CreateStandRequest) Reset()                    { *m = CreateStandRequest{} }
func (m *CreateStandRequest) String() string            { return proto1.CompactTextString(m) }
func (*CreateStandRequest) ProtoMessage()               {}
func (*CreateStandRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *CreateStandRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type UpdateStandRequest struct {
	Id    string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Title string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
}

func (m *UpdateStandRequest) Reset()                    { *m = UpdateStandRequest{} }
func (m *UpdateStandRequest) String() string            { return proto1.CompactTextString(m) }
func (*UpdateStandRequest) ProtoMessage()               {}
func (*UpdateStandRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *UpdateStandRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateStandRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type DeleteStandRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteStandRequest) Reset()                    { *m = DeleteStandRequest{} }
func (m *DeleteStandRequest) String() string            { return proto1.CompactTextString(m) }
func (*DeleteStandRequest) ProtoMessage()               {}
func (*DeleteStandRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *DeleteStandRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Stand struct {
	Id    string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Title string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
}

func (m *Stand) Reset()                    { *m = Stand{} }
func (m *Stand) String() string            { return proto1.CompactTextString(m) }
func (*Stand) ProtoMessage()               {}
func (*Stand) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Stand) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Stand) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type StandResponse struct {
	Stands []*Stand `protobuf:"bytes,1,rep,name=stands" json:"stands,omitempty"`
}

func (m *StandResponse) Reset()                    { *m = StandResponse{} }
func (m *StandResponse) String() string            { return proto1.CompactTextString(m) }
func (*StandResponse) ProtoMessage()               {}
func (*StandResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *StandResponse) GetStands() []*Stand {
	if m != nil {
		return m.Stands
	}
	return nil
}

// Additional Service ----------------------------------------------------------------
type GetAllAddRequest struct {
}

func (m *GetAllAddRequest) Reset()                    { *m = GetAllAddRequest{} }
func (m *GetAllAddRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetAllAddRequest) ProtoMessage()               {}
func (*GetAllAddRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type CreateAddRequest struct {
	Materials   string `protobuf:"bytes,1,opt,name=materials" json:"materials,omitempty"`
	Mod         string `protobuf:"bytes,2,opt,name=mod" json:"mod,omitempty"`
	Temperature string `protobuf:"bytes,3,opt,name=temperature" json:"temperature,omitempty"`
	Mounting    string `protobuf:"bytes,4,opt,name=mounting" json:"mounting,omitempty"`
	Graphite    string `protobuf:"bytes,5,opt,name=graphite" json:"graphite,omitempty"`
	TypeFl      string `protobuf:"bytes,6,opt,name=typeFl" json:"typeFl,omitempty"`
}

func (m *CreateAddRequest) Reset()                    { *m = CreateAddRequest{} }
func (m *CreateAddRequest) String() string            { return proto1.CompactTextString(m) }
func (*CreateAddRequest) ProtoMessage()               {}
func (*CreateAddRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *CreateAddRequest) GetMaterials() string {
	if m != nil {
		return m.Materials
	}
	return ""
}

func (m *CreateAddRequest) GetMod() string {
	if m != nil {
		return m.Mod
	}
	return ""
}

func (m *CreateAddRequest) GetTemperature() string {
	if m != nil {
		return m.Temperature
	}
	return ""
}

func (m *CreateAddRequest) GetMounting() string {
	if m != nil {
		return m.Mounting
	}
	return ""
}

func (m *CreateAddRequest) GetGraphite() string {
	if m != nil {
		return m.Graphite
	}
	return ""
}

func (m *CreateAddRequest) GetTypeFl() string {
	if m != nil {
		return m.TypeFl
	}
	return ""
}

type UpdateAddMatRequest struct {
	Id        string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Materials string `protobuf:"bytes,2,opt,name=materials" json:"materials,omitempty"`
}

func (m *UpdateAddMatRequest) Reset()                    { *m = UpdateAddMatRequest{} }
func (m *UpdateAddMatRequest) String() string            { return proto1.CompactTextString(m) }
func (*UpdateAddMatRequest) ProtoMessage()               {}
func (*UpdateAddMatRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *UpdateAddMatRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateAddMatRequest) GetMaterials() string {
	if m != nil {
		return m.Materials
	}
	return ""
}

type UpdateAddModRequest struct {
	Id  string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Mod string `protobuf:"bytes,2,opt,name=mod" json:"mod,omitempty"`
}

func (m *UpdateAddModRequest) Reset()                    { *m = UpdateAddModRequest{} }
func (m *UpdateAddModRequest) String() string            { return proto1.CompactTextString(m) }
func (*UpdateAddModRequest) ProtoMessage()               {}
func (*UpdateAddModRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *UpdateAddModRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateAddModRequest) GetMod() string {
	if m != nil {
		return m.Mod
	}
	return ""
}

type UpdateAddTemRequest struct {
	Id          string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Temperature string `protobuf:"bytes,2,opt,name=temperature" json:"temperature,omitempty"`
}

func (m *UpdateAddTemRequest) Reset()                    { *m = UpdateAddTemRequest{} }
func (m *UpdateAddTemRequest) String() string            { return proto1.CompactTextString(m) }
func (*UpdateAddTemRequest) ProtoMessage()               {}
func (*UpdateAddTemRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *UpdateAddTemRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateAddTemRequest) GetTemperature() string {
	if m != nil {
		return m.Temperature
	}
	return ""
}

type UpdateAddMounRequest struct {
	Id       string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Mounting string `protobuf:"bytes,2,opt,name=mounting" json:"mounting,omitempty"`
}

func (m *UpdateAddMounRequest) Reset()                    { *m = UpdateAddMounRequest{} }
func (m *UpdateAddMounRequest) String() string            { return proto1.CompactTextString(m) }
func (*UpdateAddMounRequest) ProtoMessage()               {}
func (*UpdateAddMounRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *UpdateAddMounRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateAddMounRequest) GetMounting() string {
	if m != nil {
		return m.Mounting
	}
	return ""
}

type UpdateAddGrapRequest struct {
	Id       string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Graphite string `protobuf:"bytes,2,opt,name=graphite" json:"graphite,omitempty"`
}

func (m *UpdateAddGrapRequest) Reset()                    { *m = UpdateAddGrapRequest{} }
func (m *UpdateAddGrapRequest) String() string            { return proto1.CompactTextString(m) }
func (*UpdateAddGrapRequest) ProtoMessage()               {}
func (*UpdateAddGrapRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *UpdateAddGrapRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateAddGrapRequest) GetGraphite() string {
	if m != nil {
		return m.Graphite
	}
	return ""
}

type UpdateAddTypeFlRequest struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	TypeFl string `protobuf:"bytes,2,opt,name=typeFl" json:"typeFl,omitempty"`
}

func (m *UpdateAddTypeFlRequest) Reset()                    { *m = UpdateAddTypeFlRequest{} }
func (m *UpdateAddTypeFlRequest) String() string            { return proto1.CompactTextString(m) }
func (*UpdateAddTypeFlRequest) ProtoMessage()               {}
func (*UpdateAddTypeFlRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *UpdateAddTypeFlRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateAddTypeFlRequest) GetTypeFl() string {
	if m != nil {
		return m.TypeFl
	}
	return ""
}

type Additional struct {
	Id          string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Materials   string `protobuf:"bytes,2,opt,name=materials" json:"materials,omitempty"`
	Mod         string `protobuf:"bytes,3,opt,name=mod" json:"mod,omitempty"`
	Temperature string `protobuf:"bytes,4,opt,name=temperature" json:"temperature,omitempty"`
	Mounting    string `protobuf:"bytes,5,opt,name=mounting" json:"mounting,omitempty"`
	Graphite    string `protobuf:"bytes,6,opt,name=graphite" json:"graphite,omitempty"`
	TypeFl      string `protobuf:"bytes,7,opt,name=typeFl" json:"typeFl,omitempty"`
}

func (m *Additional) Reset()                    { *m = Additional{} }
func (m *Additional) String() string            { return proto1.CompactTextString(m) }
func (*Additional) ProtoMessage()               {}
func (*Additional) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *Additional) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Additional) GetMaterials() string {
	if m != nil {
		return m.Materials
	}
	return ""
}

func (m *Additional) GetMod() string {
	if m != nil {
		return m.Mod
	}
	return ""
}

func (m *Additional) GetTemperature() string {
	if m != nil {
		return m.Temperature
	}
	return ""
}

func (m *Additional) GetMounting() string {
	if m != nil {
		return m.Mounting
	}
	return ""
}

func (m *Additional) GetGraphite() string {
	if m != nil {
		return m.Graphite
	}
	return ""
}

func (m *Additional) GetTypeFl() string {
	if m != nil {
		return m.TypeFl
	}
	return ""
}

type AdditionalResponse struct {
	Additionals []*Additional `protobuf:"bytes,1,rep,name=additionals" json:"additionals,omitempty"`
}

func (m *AdditionalResponse) Reset()                    { *m = AdditionalResponse{} }
func (m *AdditionalResponse) String() string            { return proto1.CompactTextString(m) }
func (*AdditionalResponse) ProtoMessage()               {}
func (*AdditionalResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *AdditionalResponse) GetAdditionals() []*Additional {
	if m != nil {
		return m.Additionals
	}
	return nil
}

type SuccessResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *SuccessResponse) Reset()                    { *m = SuccessResponse{} }
func (m *SuccessResponse) String() string            { return proto1.CompactTextString(m) }
func (*SuccessResponse) ProtoMessage()               {}
func (*SuccessResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *SuccessResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

// Size Service ----------------------------------------------------------------
type GetSizesRequest struct {
	Flange  string `protobuf:"bytes,1,opt,name=flange" json:"flange,omitempty"`
	TypeFl  string `protobuf:"bytes,2,opt,name=typeFl" json:"typeFl,omitempty"`
	TypePr  string `protobuf:"bytes,3,opt,name=typePr" json:"typePr,omitempty"`
	StandId string `protobuf:"bytes,4,opt,name=standId" json:"standId,omitempty"`
}

func (m *GetSizesRequest) Reset()                    { *m = GetSizesRequest{} }
func (m *GetSizesRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetSizesRequest) ProtoMessage()               {}
func (*GetSizesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *GetSizesRequest) GetFlange() string {
	if m != nil {
		return m.Flange
	}
	return ""
}

func (m *GetSizesRequest) GetTypeFl() string {
	if m != nil {
		return m.TypeFl
	}
	return ""
}

func (m *GetSizesRequest) GetTypePr() string {
	if m != nil {
		return m.TypePr
	}
	return ""
}

func (m *GetSizesRequest) GetStandId() string {
	if m != nil {
		return m.StandId
	}
	return ""
}

type CreateSizeRequest struct {
	Flange  string `protobuf:"bytes,1,opt,name=flange" json:"flange,omitempty"`
	TypeFl  string `protobuf:"bytes,2,opt,name=typeFl" json:"typeFl,omitempty"`
	Dn      int32  `protobuf:"varint,3,opt,name=dn" json:"dn,omitempty"`
	Pn      int32  `protobuf:"varint,4,opt,name=pn" json:"pn,omitempty"`
	TypePr  string `protobuf:"bytes,5,opt,name=typePr" json:"typePr,omitempty"`
	StandId string `protobuf:"bytes,6,opt,name=standId" json:"standId,omitempty"`
	D4      int32  `protobuf:"varint,7,opt,name=d4" json:"d4,omitempty"`
	D3      int32  `protobuf:"varint,8,opt,name=d3" json:"d3,omitempty"`
	D2      int32  `protobuf:"varint,9,opt,name=d2" json:"d2,omitempty"`
	D1      int32  `protobuf:"varint,10,opt,name=d1" json:"d1,omitempty"`
	H       int32  `protobuf:"varint,11,opt,name=h" json:"h,omitempty"`
}

func (m *CreateSizeRequest) Reset()                    { *m = CreateSizeRequest{} }
func (m *CreateSizeRequest) String() string            { return proto1.CompactTextString(m) }
func (*CreateSizeRequest) ProtoMessage()               {}
func (*CreateSizeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *CreateSizeRequest) GetFlange() string {
	if m != nil {
		return m.Flange
	}
	return ""
}

func (m *CreateSizeRequest) GetTypeFl() string {
	if m != nil {
		return m.TypeFl
	}
	return ""
}

func (m *CreateSizeRequest) GetDn() int32 {
	if m != nil {
		return m.Dn
	}
	return 0
}

func (m *CreateSizeRequest) GetPn() int32 {
	if m != nil {
		return m.Pn
	}
	return 0
}

func (m *CreateSizeRequest) GetTypePr() string {
	if m != nil {
		return m.TypePr
	}
	return ""
}

func (m *CreateSizeRequest) GetStandId() string {
	if m != nil {
		return m.StandId
	}
	return ""
}

func (m *CreateSizeRequest) GetD4() int32 {
	if m != nil {
		return m.D4
	}
	return 0
}

func (m *CreateSizeRequest) GetD3() int32 {
	if m != nil {
		return m.D3
	}
	return 0
}

func (m *CreateSizeRequest) GetD2() int32 {
	if m != nil {
		return m.D2
	}
	return 0
}

func (m *CreateSizeRequest) GetD1() int32 {
	if m != nil {
		return m.D1
	}
	return 0
}

func (m *CreateSizeRequest) GetH() int32 {
	if m != nil {
		return m.H
	}
	return 0
}

type UpdateSizeRequest struct {
	Flange  string `protobuf:"bytes,1,opt,name=flange" json:"flange,omitempty"`
	TypeFl  string `protobuf:"bytes,2,opt,name=typeFl" json:"typeFl,omitempty"`
	Id      string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
	Dn      int32  `protobuf:"varint,4,opt,name=dn" json:"dn,omitempty"`
	Pn      int32  `protobuf:"varint,5,opt,name=pn" json:"pn,omitempty"`
	TypePr  string `protobuf:"bytes,6,opt,name=typePr" json:"typePr,omitempty"`
	StandId string `protobuf:"bytes,7,opt,name=standId" json:"standId,omitempty"`
	D4      int32  `protobuf:"varint,8,opt,name=d4" json:"d4,omitempty"`
	D3      int32  `protobuf:"varint,9,opt,name=d3" json:"d3,omitempty"`
	D2      int32  `protobuf:"varint,10,opt,name=d2" json:"d2,omitempty"`
	D1      int32  `protobuf:"varint,11,opt,name=d1" json:"d1,omitempty"`
	H       int32  `protobuf:"varint,12,opt,name=h" json:"h,omitempty"`
}

func (m *UpdateSizeRequest) Reset()                    { *m = UpdateSizeRequest{} }
func (m *UpdateSizeRequest) String() string            { return proto1.CompactTextString(m) }
func (*UpdateSizeRequest) ProtoMessage()               {}
func (*UpdateSizeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *UpdateSizeRequest) GetFlange() string {
	if m != nil {
		return m.Flange
	}
	return ""
}

func (m *UpdateSizeRequest) GetTypeFl() string {
	if m != nil {
		return m.TypeFl
	}
	return ""
}

func (m *UpdateSizeRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateSizeRequest) GetDn() int32 {
	if m != nil {
		return m.Dn
	}
	return 0
}

func (m *UpdateSizeRequest) GetPn() int32 {
	if m != nil {
		return m.Pn
	}
	return 0
}

func (m *UpdateSizeRequest) GetTypePr() string {
	if m != nil {
		return m.TypePr
	}
	return ""
}

func (m *UpdateSizeRequest) GetStandId() string {
	if m != nil {
		return m.StandId
	}
	return ""
}

func (m *UpdateSizeRequest) GetD4() int32 {
	if m != nil {
		return m.D4
	}
	return 0
}

func (m *UpdateSizeRequest) GetD3() int32 {
	if m != nil {
		return m.D3
	}
	return 0
}

func (m *UpdateSizeRequest) GetD2() int32 {
	if m != nil {
		return m.D2
	}
	return 0
}

func (m *UpdateSizeRequest) GetD1() int32 {
	if m != nil {
		return m.D1
	}
	return 0
}

func (m *UpdateSizeRequest) GetH() int32 {
	if m != nil {
		return m.H
	}
	return 0
}

type DeleteSizeRequest struct {
	Flange string `protobuf:"bytes,1,opt,name=flange" json:"flange,omitempty"`
	TypeFl string `protobuf:"bytes,2,opt,name=typeFl" json:"typeFl,omitempty"`
	Id     string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteSizeRequest) Reset()                    { *m = DeleteSizeRequest{} }
func (m *DeleteSizeRequest) String() string            { return proto1.CompactTextString(m) }
func (*DeleteSizeRequest) ProtoMessage()               {}
func (*DeleteSizeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *DeleteSizeRequest) GetFlange() string {
	if m != nil {
		return m.Flange
	}
	return ""
}

func (m *DeleteSizeRequest) GetTypeFl() string {
	if m != nil {
		return m.TypeFl
	}
	return ""
}

func (m *DeleteSizeRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Size struct {
	Id      string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Dn      int32  `protobuf:"varint,2,opt,name=dn" json:"dn,omitempty"`
	Pn      int32  `protobuf:"varint,3,opt,name=pn" json:"pn,omitempty"`
	TypePr  string `protobuf:"bytes,4,opt,name=typePr" json:"typePr,omitempty"`
	StandId string `protobuf:"bytes,5,opt,name=standId" json:"standId,omitempty"`
	D4      int32  `protobuf:"varint,6,opt,name=d4" json:"d4,omitempty"`
	D3      int32  `protobuf:"varint,7,opt,name=d3" json:"d3,omitempty"`
	D2      int32  `protobuf:"varint,8,opt,name=d2" json:"d2,omitempty"`
	D1      int32  `protobuf:"varint,9,opt,name=d1" json:"d1,omitempty"`
	H       int32  `protobuf:"varint,10,opt,name=h" json:"h,omitempty"`
}

func (m *Size) Reset()                    { *m = Size{} }
func (m *Size) String() string            { return proto1.CompactTextString(m) }
func (*Size) ProtoMessage()               {}
func (*Size) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *Size) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Size) GetDn() int32 {
	if m != nil {
		return m.Dn
	}
	return 0
}

func (m *Size) GetPn() int32 {
	if m != nil {
		return m.Pn
	}
	return 0
}

func (m *Size) GetTypePr() string {
	if m != nil {
		return m.TypePr
	}
	return ""
}

func (m *Size) GetStandId() string {
	if m != nil {
		return m.StandId
	}
	return ""
}

func (m *Size) GetD4() int32 {
	if m != nil {
		return m.D4
	}
	return 0
}

func (m *Size) GetD3() int32 {
	if m != nil {
		return m.D3
	}
	return 0
}

func (m *Size) GetD2() int32 {
	if m != nil {
		return m.D2
	}
	return 0
}

func (m *Size) GetD1() int32 {
	if m != nil {
		return m.D1
	}
	return 0
}

func (m *Size) GetH() int32 {
	if m != nil {
		return m.H
	}
	return 0
}

type SizeResponse struct {
	Sizes []*Size `protobuf:"bytes,1,rep,name=sizes" json:"sizes,omitempty"`
}

func (m *SizeResponse) Reset()                    { *m = SizeResponse{} }
func (m *SizeResponse) String() string            { return proto1.CompactTextString(m) }
func (*SizeResponse) ProtoMessage()               {}
func (*SizeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *SizeResponse) GetSizes() []*Size {
	if m != nil {
		return m.Sizes
	}
	return nil
}

// SNP Service ----------------------------------------------------------------
type GetSNPRequest struct {
	StandId string `protobuf:"bytes,1,opt,name=standId" json:"standId,omitempty"`
	TypeFl  string `protobuf:"bytes,2,opt,name=typeFl" json:"typeFl,omitempty"`
}

func (m *GetSNPRequest) Reset()                    { *m = GetSNPRequest{} }
func (m *GetSNPRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetSNPRequest) ProtoMessage()               {}
func (*GetSNPRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *GetSNPRequest) GetStandId() string {
	if m != nil {
		return m.StandId
	}
	return ""
}

func (m *GetSNPRequest) GetTypeFl() string {
	if m != nil {
		return m.TypeFl
	}
	return ""
}

type CreateSNPRequest struct {
	StandId     string `protobuf:"bytes,1,opt,name=standId" json:"standId,omitempty"`
	TypeFl      string `protobuf:"bytes,2,opt,name=typeFl" json:"typeFl,omitempty"`
	TypeP       string `protobuf:"bytes,3,opt,name=typeP" json:"typeP,omitempty"`
	Fillers     string `protobuf:"bytes,4,opt,name=fillers" json:"fillers,omitempty"`
	Materials   string `protobuf:"bytes,5,opt,name=materials" json:"materials,omitempty"`
	Mod         string `protobuf:"bytes,6,opt,name=mod" json:"mod,omitempty"`
	Temperature string `protobuf:"bytes,7,opt,name=temperature" json:"temperature,omitempty"`
	Mounting    string `protobuf:"bytes,8,opt,name=mounting" json:"mounting,omitempty"`
	Graphite    string `protobuf:"bytes,9,opt,name=graphite" json:"graphite,omitempty"`
}

func (m *CreateSNPRequest) Reset()                    { *m = CreateSNPRequest{} }
func (m *CreateSNPRequest) String() string            { return proto1.CompactTextString(m) }
func (*CreateSNPRequest) ProtoMessage()               {}
func (*CreateSNPRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *CreateSNPRequest) GetStandId() string {
	if m != nil {
		return m.StandId
	}
	return ""
}

func (m *CreateSNPRequest) GetTypeFl() string {
	if m != nil {
		return m.TypeFl
	}
	return ""
}

func (m *CreateSNPRequest) GetTypeP() string {
	if m != nil {
		return m.TypeP
	}
	return ""
}

func (m *CreateSNPRequest) GetFillers() string {
	if m != nil {
		return m.Fillers
	}
	return ""
}

func (m *CreateSNPRequest) GetMaterials() string {
	if m != nil {
		return m.Materials
	}
	return ""
}

func (m *CreateSNPRequest) GetMod() string {
	if m != nil {
		return m.Mod
	}
	return ""
}

func (m *CreateSNPRequest) GetTemperature() string {
	if m != nil {
		return m.Temperature
	}
	return ""
}

func (m *CreateSNPRequest) GetMounting() string {
	if m != nil {
		return m.Mounting
	}
	return ""
}

func (m *CreateSNPRequest) GetGraphite() string {
	if m != nil {
		return m.Graphite
	}
	return ""
}

type UpdateSNPRequest struct {
	Id          string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	StandId     string `protobuf:"bytes,2,opt,name=standId" json:"standId,omitempty"`
	TypeFl      string `protobuf:"bytes,3,opt,name=typeFl" json:"typeFl,omitempty"`
	TypeP       string `protobuf:"bytes,4,opt,name=typeP" json:"typeP,omitempty"`
	Fillers     string `protobuf:"bytes,5,opt,name=fillers" json:"fillers,omitempty"`
	Materials   string `protobuf:"bytes,6,opt,name=materials" json:"materials,omitempty"`
	Mod         string `protobuf:"bytes,7,opt,name=mod" json:"mod,omitempty"`
	Temperature string `protobuf:"bytes,8,opt,name=temperature" json:"temperature,omitempty"`
	Mounting    string `protobuf:"bytes,9,opt,name=mounting" json:"mounting,omitempty"`
	Graphite    string `protobuf:"bytes,10,opt,name=graphite" json:"graphite,omitempty"`
}

func (m *UpdateSNPRequest) Reset()                    { *m = UpdateSNPRequest{} }
func (m *UpdateSNPRequest) String() string            { return proto1.CompactTextString(m) }
func (*UpdateSNPRequest) ProtoMessage()               {}
func (*UpdateSNPRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *UpdateSNPRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateSNPRequest) GetStandId() string {
	if m != nil {
		return m.StandId
	}
	return ""
}

func (m *UpdateSNPRequest) GetTypeFl() string {
	if m != nil {
		return m.TypeFl
	}
	return ""
}

func (m *UpdateSNPRequest) GetTypeP() string {
	if m != nil {
		return m.TypeP
	}
	return ""
}

func (m *UpdateSNPRequest) GetFillers() string {
	if m != nil {
		return m.Fillers
	}
	return ""
}

func (m *UpdateSNPRequest) GetMaterials() string {
	if m != nil {
		return m.Materials
	}
	return ""
}

func (m *UpdateSNPRequest) GetMod() string {
	if m != nil {
		return m.Mod
	}
	return ""
}

func (m *UpdateSNPRequest) GetTemperature() string {
	if m != nil {
		return m.Temperature
	}
	return ""
}

func (m *UpdateSNPRequest) GetMounting() string {
	if m != nil {
		return m.Mounting
	}
	return ""
}

func (m *UpdateSNPRequest) GetGraphite() string {
	if m != nil {
		return m.Graphite
	}
	return ""
}

type DeleteSNPRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteSNPRequest) Reset()                    { *m = DeleteSNPRequest{} }
func (m *DeleteSNPRequest) String() string            { return proto1.CompactTextString(m) }
func (*DeleteSNPRequest) ProtoMessage()               {}
func (*DeleteSNPRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

func (m *DeleteSNPRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SNP struct {
	Id          string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	StandId     string `protobuf:"bytes,2,opt,name=standId" json:"standId,omitempty"`
	TypeFl      string `protobuf:"bytes,3,opt,name=typeFl" json:"typeFl,omitempty"`
	TypeP       string `protobuf:"bytes,4,opt,name=typeP" json:"typeP,omitempty"`
	Fillers     string `protobuf:"bytes,5,opt,name=fillers" json:"fillers,omitempty"`
	Materials   string `protobuf:"bytes,6,opt,name=materials" json:"materials,omitempty"`
	Mod         string `protobuf:"bytes,7,opt,name=mod" json:"mod,omitempty"`
	Temperature string `protobuf:"bytes,8,opt,name=temperature" json:"temperature,omitempty"`
	Mounting    string `protobuf:"bytes,9,opt,name=mounting" json:"mounting,omitempty"`
	Graphite    string `protobuf:"bytes,10,opt,name=graphite" json:"graphite,omitempty"`
}

func (m *SNP) Reset()                    { *m = SNP{} }
func (m *SNP) String() string            { return proto1.CompactTextString(m) }
func (*SNP) ProtoMessage()               {}
func (*SNP) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

func (m *SNP) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SNP) GetStandId() string {
	if m != nil {
		return m.StandId
	}
	return ""
}

func (m *SNP) GetTypeFl() string {
	if m != nil {
		return m.TypeFl
	}
	return ""
}

func (m *SNP) GetTypeP() string {
	if m != nil {
		return m.TypeP
	}
	return ""
}

func (m *SNP) GetFillers() string {
	if m != nil {
		return m.Fillers
	}
	return ""
}

func (m *SNP) GetMaterials() string {
	if m != nil {
		return m.Materials
	}
	return ""
}

func (m *SNP) GetMod() string {
	if m != nil {
		return m.Mod
	}
	return ""
}

func (m *SNP) GetTemperature() string {
	if m != nil {
		return m.Temperature
	}
	return ""
}

func (m *SNP) GetMounting() string {
	if m != nil {
		return m.Mounting
	}
	return ""
}

func (m *SNP) GetGraphite() string {
	if m != nil {
		return m.Graphite
	}
	return ""
}

type SNPResponse struct {
	Snp []*SNP `protobuf:"bytes,1,rep,name=snp" json:"snp,omitempty"`
}

func (m *SNPResponse) Reset()                    { *m = SNPResponse{} }
func (m *SNPResponse) String() string            { return proto1.CompactTextString(m) }
func (*SNPResponse) ProtoMessage()               {}
func (*SNPResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

func (m *SNPResponse) GetSnp() []*SNP {
	if m != nil {
		return m.Snp
	}
	return nil
}

// commmon ----------------------------------------------------------------
type IdResponse struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *IdResponse) Reset()                    { *m = IdResponse{} }
func (m *IdResponse) String() string            { return proto1.CompactTextString(m) }
func (*IdResponse) ProtoMessage()               {}
func (*IdResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

func (m *IdResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type PingRequest struct {
}

func (m *PingRequest) Reset()                    { *m = PingRequest{} }
func (m *PingRequest) String() string            { return proto1.CompactTextString(m) }
func (*PingRequest) ProtoMessage()               {}
func (*PingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

type PingResponse struct {
	Ping string `protobuf:"bytes,1,opt,name=ping" json:"ping,omitempty"`
}

func (m *PingResponse) Reset()                    { *m = PingResponse{} }
func (m *PingResponse) String() string            { return proto1.CompactTextString(m) }
func (*PingResponse) ProtoMessage()               {}
func (*PingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{37} }

func (m *PingResponse) GetPing() string {
	if m != nil {
		return m.Ping
	}
	return ""
}

func init() {
	proto1.RegisterType((*GetAllFlangeRequest)(nil), "proto.GetAllFlangeRequest")
	proto1.RegisterType((*CreateFlangeRequest)(nil), "proto.CreateFlangeRequest")
	proto1.RegisterType((*UpdateFlangeRequest)(nil), "proto.UpdateFlangeRequest")
	proto1.RegisterType((*DeleteFlangeRequest)(nil), "proto.DeleteFlangeRequest")
	proto1.RegisterType((*Flange)(nil), "proto.Flange")
	proto1.RegisterType((*FlangeResponse)(nil), "proto.FlangeResponse")
	proto1.RegisterType((*GetStandsRequest)(nil), "proto.GetStandsRequest")
	proto1.RegisterType((*CreateStandRequest)(nil), "proto.CreateStandRequest")
	proto1.RegisterType((*UpdateStandRequest)(nil), "proto.UpdateStandRequest")
	proto1.RegisterType((*DeleteStandRequest)(nil), "proto.DeleteStandRequest")
	proto1.RegisterType((*Stand)(nil), "proto.Stand")
	proto1.RegisterType((*StandResponse)(nil), "proto.StandResponse")
	proto1.RegisterType((*GetAllAddRequest)(nil), "proto.GetAllAddRequest")
	proto1.RegisterType((*CreateAddRequest)(nil), "proto.CreateAddRequest")
	proto1.RegisterType((*UpdateAddMatRequest)(nil), "proto.UpdateAddMatRequest")
	proto1.RegisterType((*UpdateAddModRequest)(nil), "proto.UpdateAddModRequest")
	proto1.RegisterType((*UpdateAddTemRequest)(nil), "proto.UpdateAddTemRequest")
	proto1.RegisterType((*UpdateAddMounRequest)(nil), "proto.UpdateAddMounRequest")
	proto1.RegisterType((*UpdateAddGrapRequest)(nil), "proto.UpdateAddGrapRequest")
	proto1.RegisterType((*UpdateAddTypeFlRequest)(nil), "proto.UpdateAddTypeFlRequest")
	proto1.RegisterType((*Additional)(nil), "proto.Additional")
	proto1.RegisterType((*AdditionalResponse)(nil), "proto.AdditionalResponse")
	proto1.RegisterType((*SuccessResponse)(nil), "proto.SuccessResponse")
	proto1.RegisterType((*GetSizesRequest)(nil), "proto.GetSizesRequest")
	proto1.RegisterType((*CreateSizeRequest)(nil), "proto.CreateSizeRequest")
	proto1.RegisterType((*UpdateSizeRequest)(nil), "proto.UpdateSizeRequest")
	proto1.RegisterType((*DeleteSizeRequest)(nil), "proto.DeleteSizeRequest")
	proto1.RegisterType((*Size)(nil), "proto.Size")
	proto1.RegisterType((*SizeResponse)(nil), "proto.SizeResponse")
	proto1.RegisterType((*GetSNPRequest)(nil), "proto.GetSNPRequest")
	proto1.RegisterType((*CreateSNPRequest)(nil), "proto.CreateSNPRequest")
	proto1.RegisterType((*UpdateSNPRequest)(nil), "proto.UpdateSNPRequest")
	proto1.RegisterType((*DeleteSNPRequest)(nil), "proto.DeleteSNPRequest")
	proto1.RegisterType((*SNP)(nil), "proto.SNP")
	proto1.RegisterType((*SNPResponse)(nil), "proto.SNPResponse")
	proto1.RegisterType((*IdResponse)(nil), "proto.IdResponse")
	proto1.RegisterType((*PingRequest)(nil), "proto.PingRequest")
	proto1.RegisterType((*PingResponse)(nil), "proto.PingResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ProService service

type ProServiceClient interface {
	// common -----------------------------------------------------------------------
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// Flange Service ----------------------------------------------------------------
	GetAllFlanges(ctx context.Context, in *GetAllFlangeRequest, opts ...grpc.CallOption) (*FlangeResponse, error)
	CreateFlange(ctx context.Context, in *CreateFlangeRequest, opts ...grpc.CallOption) (*IdResponse, error)
	UpdateFlange(ctx context.Context, in *UpdateFlangeRequest, opts ...grpc.CallOption) (*IdResponse, error)
	DeleteFlange(ctx context.Context, in *DeleteFlangeRequest, opts ...grpc.CallOption) (*IdResponse, error)
	// Stand Service ----------------------------------------------------------------
	GetAllStands(ctx context.Context, in *GetStandsRequest, opts ...grpc.CallOption) (*StandResponse, error)
	CreateStand(ctx context.Context, in *CreateStandRequest, opts ...grpc.CallOption) (*IdResponse, error)
	UpdateStand(ctx context.Context, in *UpdateStandRequest, opts ...grpc.CallOption) (*IdResponse, error)
	DeleteStand(ctx context.Context, in *DeleteStandRequest, opts ...grpc.CallOption) (*IdResponse, error)
	// Additional Service ----------------------------------------------------------------
	GetAllAdditional(ctx context.Context, in *GetAllAddRequest, opts ...grpc.CallOption) (*AdditionalResponse, error)
	CreateAdditional(ctx context.Context, in *CreateAddRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
	UpdateMat(ctx context.Context, in *UpdateAddMatRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
	UpdateMod(ctx context.Context, in *UpdateAddModRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
	UpdateTemp(ctx context.Context, in *UpdateAddTemRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
	UpdateMoun(ctx context.Context, in *UpdateAddMounRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
	UpdateGrap(ctx context.Context, in *UpdateAddGrapRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
	UpdateTypeFl(ctx context.Context, in *UpdateAddTypeFlRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
	// Size Service ----------------------------------------------------------------
	GetSizes(ctx context.Context, in *GetSizesRequest, opts ...grpc.CallOption) (*SizeResponse, error)
	CreateSize(ctx context.Context, in *CreateSizeRequest, opts ...grpc.CallOption) (*IdResponse, error)
	UpdateSize(ctx context.Context, in *UpdateSizeRequest, opts ...grpc.CallOption) (*IdResponse, error)
	DeleteSize(ctx context.Context, in *DeleteSizeRequest, opts ...grpc.CallOption) (*IdResponse, error)
	// SNP Service ----------------------------------------------------------------
	GetSNP(ctx context.Context, in *GetSNPRequest, opts ...grpc.CallOption) (*SNPResponse, error)
	CreateSNP(ctx context.Context, in *CreateSNPRequest, opts ...grpc.CallOption) (*IdResponse, error)
	UpdateSNP(ctx context.Context, in *UpdateSNPRequest, opts ...grpc.CallOption) (*IdResponse, error)
	DeleteSNP(ctx context.Context, in *DeleteSNPRequest, opts ...grpc.CallOption) (*IdResponse, error)
}

type proServiceClient struct {
	cc *grpc.ClientConn
}

func NewProServiceClient(cc *grpc.ClientConn) ProServiceClient {
	return &proServiceClient{cc}
}

func (c *proServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := grpc.Invoke(ctx, "/proto.ProService/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proServiceClient) GetAllFlanges(ctx context.Context, in *GetAllFlangeRequest, opts ...grpc.CallOption) (*FlangeResponse, error) {
	out := new(FlangeResponse)
	err := grpc.Invoke(ctx, "/proto.ProService/GetAllFlanges", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proServiceClient) CreateFlange(ctx context.Context, in *CreateFlangeRequest, opts ...grpc.CallOption) (*IdResponse, error) {
	out := new(IdResponse)
	err := grpc.Invoke(ctx, "/proto.ProService/CreateFlange", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proServiceClient) UpdateFlange(ctx context.Context, in *UpdateFlangeRequest, opts ...grpc.CallOption) (*IdResponse, error) {
	out := new(IdResponse)
	err := grpc.Invoke(ctx, "/proto.ProService/UpdateFlange", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proServiceClient) DeleteFlange(ctx context.Context, in *DeleteFlangeRequest, opts ...grpc.CallOption) (*IdResponse, error) {
	out := new(IdResponse)
	err := grpc.Invoke(ctx, "/proto.ProService/DeleteFlange", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proServiceClient) GetAllStands(ctx context.Context, in *GetStandsRequest, opts ...grpc.CallOption) (*StandResponse, error) {
	out := new(StandResponse)
	err := grpc.Invoke(ctx, "/proto.ProService/GetAllStands", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proServiceClient) CreateStand(ctx context.Context, in *CreateStandRequest, opts ...grpc.CallOption) (*IdResponse, error) {
	out := new(IdResponse)
	err := grpc.Invoke(ctx, "/proto.ProService/CreateStand", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proServiceClient) UpdateStand(ctx context.Context, in *UpdateStandRequest, opts ...grpc.CallOption) (*IdResponse, error) {
	out := new(IdResponse)
	err := grpc.Invoke(ctx, "/proto.ProService/UpdateStand", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proServiceClient) DeleteStand(ctx context.Context, in *DeleteStandRequest, opts ...grpc.CallOption) (*IdResponse, error) {
	out := new(IdResponse)
	err := grpc.Invoke(ctx, "/proto.ProService/DeleteStand", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proServiceClient) GetAllAdditional(ctx context.Context, in *GetAllAddRequest, opts ...grpc.CallOption) (*AdditionalResponse, error) {
	out := new(AdditionalResponse)
	err := grpc.Invoke(ctx, "/proto.ProService/GetAllAdditional", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proServiceClient) CreateAdditional(ctx context.Context, in *CreateAddRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	out := new(SuccessResponse)
	err := grpc.Invoke(ctx, "/proto.ProService/CreateAdditional", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proServiceClient) UpdateMat(ctx context.Context, in *UpdateAddMatRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	out := new(SuccessResponse)
	err := grpc.Invoke(ctx, "/proto.ProService/UpdateMat", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proServiceClient) UpdateMod(ctx context.Context, in *UpdateAddModRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	out := new(SuccessResponse)
	err := grpc.Invoke(ctx, "/proto.ProService/UpdateMod", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proServiceClient) UpdateTemp(ctx context.Context, in *UpdateAddTemRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	out := new(SuccessResponse)
	err := grpc.Invoke(ctx, "/proto.ProService/UpdateTemp", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proServiceClient) UpdateMoun(ctx context.Context, in *UpdateAddMounRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	out := new(SuccessResponse)
	err := grpc.Invoke(ctx, "/proto.ProService/UpdateMoun", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proServiceClient) UpdateGrap(ctx context.Context, in *UpdateAddGrapRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	out := new(SuccessResponse)
	err := grpc.Invoke(ctx, "/proto.ProService/UpdateGrap", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proServiceClient) UpdateTypeFl(ctx context.Context, in *UpdateAddTypeFlRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	out := new(SuccessResponse)
	err := grpc.Invoke(ctx, "/proto.ProService/UpdateTypeFl", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proServiceClient) GetSizes(ctx context.Context, in *GetSizesRequest, opts ...grpc.CallOption) (*SizeResponse, error) {
	out := new(SizeResponse)
	err := grpc.Invoke(ctx, "/proto.ProService/GetSizes", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proServiceClient) CreateSize(ctx context.Context, in *CreateSizeRequest, opts ...grpc.CallOption) (*IdResponse, error) {
	out := new(IdResponse)
	err := grpc.Invoke(ctx, "/proto.ProService/CreateSize", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proServiceClient) UpdateSize(ctx context.Context, in *UpdateSizeRequest, opts ...grpc.CallOption) (*IdResponse, error) {
	out := new(IdResponse)
	err := grpc.Invoke(ctx, "/proto.ProService/UpdateSize", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proServiceClient) DeleteSize(ctx context.Context, in *DeleteSizeRequest, opts ...grpc.CallOption) (*IdResponse, error) {
	out := new(IdResponse)
	err := grpc.Invoke(ctx, "/proto.ProService/DeleteSize", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proServiceClient) GetSNP(ctx context.Context, in *GetSNPRequest, opts ...grpc.CallOption) (*SNPResponse, error) {
	out := new(SNPResponse)
	err := grpc.Invoke(ctx, "/proto.ProService/GetSNP", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proServiceClient) CreateSNP(ctx context.Context, in *CreateSNPRequest, opts ...grpc.CallOption) (*IdResponse, error) {
	out := new(IdResponse)
	err := grpc.Invoke(ctx, "/proto.ProService/CreateSNP", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proServiceClient) UpdateSNP(ctx context.Context, in *UpdateSNPRequest, opts ...grpc.CallOption) (*IdResponse, error) {
	out := new(IdResponse)
	err := grpc.Invoke(ctx, "/proto.ProService/UpdateSNP", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proServiceClient) DeleteSNP(ctx context.Context, in *DeleteSNPRequest, opts ...grpc.CallOption) (*IdResponse, error) {
	out := new(IdResponse)
	err := grpc.Invoke(ctx, "/proto.ProService/DeleteSNP", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ProService service

type ProServiceServer interface {
	// common -----------------------------------------------------------------------
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// Flange Service ----------------------------------------------------------------
	GetAllFlanges(context.Context, *GetAllFlangeRequest) (*FlangeResponse, error)
	CreateFlange(context.Context, *CreateFlangeRequest) (*IdResponse, error)
	UpdateFlange(context.Context, *UpdateFlangeRequest) (*IdResponse, error)
	DeleteFlange(context.Context, *DeleteFlangeRequest) (*IdResponse, error)
	// Stand Service ----------------------------------------------------------------
	GetAllStands(context.Context, *GetStandsRequest) (*StandResponse, error)
	CreateStand(context.Context, *CreateStandRequest) (*IdResponse, error)
	UpdateStand(context.Context, *UpdateStandRequest) (*IdResponse, error)
	DeleteStand(context.Context, *DeleteStandRequest) (*IdResponse, error)
	// Additional Service ----------------------------------------------------------------
	GetAllAdditional(context.Context, *GetAllAddRequest) (*AdditionalResponse, error)
	CreateAdditional(context.Context, *CreateAddRequest) (*SuccessResponse, error)
	UpdateMat(context.Context, *UpdateAddMatRequest) (*SuccessResponse, error)
	UpdateMod(context.Context, *UpdateAddModRequest) (*SuccessResponse, error)
	UpdateTemp(context.Context, *UpdateAddTemRequest) (*SuccessResponse, error)
	UpdateMoun(context.Context, *UpdateAddMounRequest) (*SuccessResponse, error)
	UpdateGrap(context.Context, *UpdateAddGrapRequest) (*SuccessResponse, error)
	UpdateTypeFl(context.Context, *UpdateAddTypeFlRequest) (*SuccessResponse, error)
	// Size Service ----------------------------------------------------------------
	GetSizes(context.Context, *GetSizesRequest) (*SizeResponse, error)
	CreateSize(context.Context, *CreateSizeRequest) (*IdResponse, error)
	UpdateSize(context.Context, *UpdateSizeRequest) (*IdResponse, error)
	DeleteSize(context.Context, *DeleteSizeRequest) (*IdResponse, error)
	// SNP Service ----------------------------------------------------------------
	GetSNP(context.Context, *GetSNPRequest) (*SNPResponse, error)
	CreateSNP(context.Context, *CreateSNPRequest) (*IdResponse, error)
	UpdateSNP(context.Context, *UpdateSNPRequest) (*IdResponse, error)
	DeleteSNP(context.Context, *DeleteSNPRequest) (*IdResponse, error)
}

func RegisterProServiceServer(s *grpc.Server, srv ProServiceServer) {
	s.RegisterService(&_ProService_serviceDesc, srv)
}

func _ProService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProService_GetAllFlanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllFlangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProServiceServer).GetAllFlanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProService/GetAllFlanges",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProServiceServer).GetAllFlanges(ctx, req.(*GetAllFlangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProService_CreateFlange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFlangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProServiceServer).CreateFlange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProService/CreateFlange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProServiceServer).CreateFlange(ctx, req.(*CreateFlangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProService_UpdateFlange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFlangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProServiceServer).UpdateFlange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProService/UpdateFlange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProServiceServer).UpdateFlange(ctx, req.(*UpdateFlangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProService_DeleteFlange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFlangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProServiceServer).DeleteFlange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProService/DeleteFlange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProServiceServer).DeleteFlange(ctx, req.(*DeleteFlangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProService_GetAllStands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStandsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProServiceServer).GetAllStands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProService/GetAllStands",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProServiceServer).GetAllStands(ctx, req.(*GetStandsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProService_CreateStand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProServiceServer).CreateStand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProService/CreateStand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProServiceServer).CreateStand(ctx, req.(*CreateStandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProService_UpdateStand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProServiceServer).UpdateStand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProService/UpdateStand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProServiceServer).UpdateStand(ctx, req.(*UpdateStandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProService_DeleteStand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProServiceServer).DeleteStand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProService/DeleteStand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProServiceServer).DeleteStand(ctx, req.(*DeleteStandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProService_GetAllAdditional_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProServiceServer).GetAllAdditional(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProService/GetAllAdditional",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProServiceServer).GetAllAdditional(ctx, req.(*GetAllAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProService_CreateAdditional_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProServiceServer).CreateAdditional(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProService/CreateAdditional",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProServiceServer).CreateAdditional(ctx, req.(*CreateAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProService_UpdateMat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAddMatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProServiceServer).UpdateMat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProService/UpdateMat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProServiceServer).UpdateMat(ctx, req.(*UpdateAddMatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProService_UpdateMod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAddModRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProServiceServer).UpdateMod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProService/UpdateMod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProServiceServer).UpdateMod(ctx, req.(*UpdateAddModRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProService_UpdateTemp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAddTemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProServiceServer).UpdateTemp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProService/UpdateTemp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProServiceServer).UpdateTemp(ctx, req.(*UpdateAddTemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProService_UpdateMoun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAddMounRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProServiceServer).UpdateMoun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProService/UpdateMoun",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProServiceServer).UpdateMoun(ctx, req.(*UpdateAddMounRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProService_UpdateGrap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAddGrapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProServiceServer).UpdateGrap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProService/UpdateGrap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProServiceServer).UpdateGrap(ctx, req.(*UpdateAddGrapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProService_UpdateTypeFl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAddTypeFlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProServiceServer).UpdateTypeFl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProService/UpdateTypeFl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProServiceServer).UpdateTypeFl(ctx, req.(*UpdateAddTypeFlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProService_GetSizes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSizesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProServiceServer).GetSizes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProService/GetSizes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProServiceServer).GetSizes(ctx, req.(*GetSizesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProService_CreateSize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProServiceServer).CreateSize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProService/CreateSize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProServiceServer).CreateSize(ctx, req.(*CreateSizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProService_UpdateSize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProServiceServer).UpdateSize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProService/UpdateSize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProServiceServer).UpdateSize(ctx, req.(*UpdateSizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProService_DeleteSize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProServiceServer).DeleteSize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProService/DeleteSize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProServiceServer).DeleteSize(ctx, req.(*DeleteSizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProService_GetSNP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSNPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProServiceServer).GetSNP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProService/GetSNP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProServiceServer).GetSNP(ctx, req.(*GetSNPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProService_CreateSNP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSNPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProServiceServer).CreateSNP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProService/CreateSNP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProServiceServer).CreateSNP(ctx, req.(*CreateSNPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProService_UpdateSNP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSNPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProServiceServer).UpdateSNP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProService/UpdateSNP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProServiceServer).UpdateSNP(ctx, req.(*UpdateSNPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProService_DeleteSNP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSNPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProServiceServer).DeleteSNP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProService/DeleteSNP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProServiceServer).DeleteSNP(ctx, req.(*DeleteSNPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ProService",
	HandlerType: (*ProServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _ProService_Ping_Handler,
		},
		{
			MethodName: "GetAllFlanges",
			Handler:    _ProService_GetAllFlanges_Handler,
		},
		{
			MethodName: "CreateFlange",
			Handler:    _ProService_CreateFlange_Handler,
		},
		{
			MethodName: "UpdateFlange",
			Handler:    _ProService_UpdateFlange_Handler,
		},
		{
			MethodName: "DeleteFlange",
			Handler:    _ProService_DeleteFlange_Handler,
		},
		{
			MethodName: "GetAllStands",
			Handler:    _ProService_GetAllStands_Handler,
		},
		{
			MethodName: "CreateStand",
			Handler:    _ProService_CreateStand_Handler,
		},
		{
			MethodName: "UpdateStand",
			Handler:    _ProService_UpdateStand_Handler,
		},
		{
			MethodName: "DeleteStand",
			Handler:    _ProService_DeleteStand_Handler,
		},
		{
			MethodName: "GetAllAdditional",
			Handler:    _ProService_GetAllAdditional_Handler,
		},
		{
			MethodName: "CreateAdditional",
			Handler:    _ProService_CreateAdditional_Handler,
		},
		{
			MethodName: "UpdateMat",
			Handler:    _ProService_UpdateMat_Handler,
		},
		{
			MethodName: "UpdateMod",
			Handler:    _ProService_UpdateMod_Handler,
		},
		{
			MethodName: "UpdateTemp",
			Handler:    _ProService_UpdateTemp_Handler,
		},
		{
			MethodName: "UpdateMoun",
			Handler:    _ProService_UpdateMoun_Handler,
		},
		{
			MethodName: "UpdateGrap",
			Handler:    _ProService_UpdateGrap_Handler,
		},
		{
			MethodName: "UpdateTypeFl",
			Handler:    _ProService_UpdateTypeFl_Handler,
		},
		{
			MethodName: "GetSizes",
			Handler:    _ProService_GetSizes_Handler,
		},
		{
			MethodName: "CreateSize",
			Handler:    _ProService_CreateSize_Handler,
		},
		{
			MethodName: "UpdateSize",
			Handler:    _ProService_UpdateSize_Handler,
		},
		{
			MethodName: "DeleteSize",
			Handler:    _ProService_DeleteSize_Handler,
		},
		{
			MethodName: "GetSNP",
			Handler:    _ProService_GetSNP_Handler,
		},
		{
			MethodName: "CreateSNP",
			Handler:    _ProService_CreateSNP_Handler,
		},
		{
			MethodName: "UpdateSNP",
			Handler:    _ProService_UpdateSNP_Handler,
		},
		{
			MethodName: "DeleteSNP",
			Handler:    _ProService_DeleteSNP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/pro.proto",
}

func init() { proto1.RegisterFile("proto/pro.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x57, 0xdd, 0x6e, 0xdc, 0x44,
	0x14, 0x96, 0xbd, 0x6b, 0xef, 0xee, 0xd9, 0x4d, 0x9b, 0x4c, 0xd2, 0xd4, 0x5d, 0x82, 0x14, 0x46,
	0x45, 0x54, 0x54, 0x24, 0x4a, 0x52, 0x14, 0x85, 0xa8, 0xa2, 0x9b, 0x94, 0x44, 0xb9, 0x68, 0xb4,
	0x6c, 0xca, 0x0d, 0x77, 0x26, 0x9e, 0x26, 0x96, 0xbc, 0xb6, 0xb1, 0x1d, 0x24, 0x7a, 0xc7, 0x0b,
	0xf0, 0x02, 0xbc, 0x06, 0xe2, 0x92, 0x97, 0xe1, 0x11, 0xb8, 0x47, 0xc8, 0xf3, 0x63, 0xcf, 0x8c,
	0x3d, 0x9b, 0x40, 0xb8, 0xe3, 0x6a, 0xf7, 0x8c, 0xe7, 0x7c, 0x33, 0xe7, 0x9b, 0x39, 0x67, 0xce,
	0x07, 0x0f, 0xd3, 0x2c, 0x29, 0x92, 0xed, 0x34, 0x4b, 0xb6, 0xe8, 0x3f, 0xe4, 0xd0, 0x1f, 0xfc,
	0x08, 0x56, 0x4f, 0x49, 0x31, 0x89, 0xa2, 0x93, 0xc8, 0x8f, 0xaf, 0xc8, 0x8c, 0x7c, 0x7f, 0x43,
	0xf2, 0x02, 0x4f, 0x60, 0xf5, 0x38, 0x23, 0x7e, 0x41, 0x94, 0x61, 0xb4, 0x06, 0x4e, 0x11, 0x16,
	0x11, 0xf1, 0xac, 0x4d, 0xeb, 0xd9, 0x60, 0xc6, 0x8c, 0x72, 0x34, 0xbf, 0x4e, 0xb2, 0xc2, 0xb3,
	0xd9, 0x28, 0x35, 0xf0, 0xd7, 0xb0, 0xfa, 0x4d, 0x1a, 0x34, 0x20, 0x1e, 0x80, 0x1d, 0x06, 0xdc,
	0xdf, 0x0e, 0x83, 0x1a, 0xd2, 0x6e, 0x85, 0xec, 0xc8, 0x90, 0x1f, 0xc3, 0xea, 0x6b, 0x12, 0x91,
	0x5b, 0x20, 0xf1, 0x6b, 0x70, 0xd9, 0x84, 0x7b, 0x2d, 0x76, 0x00, 0x0f, 0xc4, 0x32, 0x79, 0x9a,
	0xc4, 0x39, 0x41, 0x9f, 0x40, 0xef, 0x1d, 0x1d, 0xc9, 0x3d, 0x6b, 0xb3, 0xf3, 0x6c, 0xb8, 0xbb,
	0xc4, 0xb8, 0xdc, 0xe2, 0xf3, 0xc4, 0x57, 0x8c, 0x60, 0xf9, 0x94, 0x14, 0x17, 0x85, 0x1f, 0x07,
	0xb9, 0x60, 0xf4, 0x53, 0x40, 0x8c, 0x51, 0x3a, 0xbc, 0x90, 0x50, 0xfc, 0x05, 0x20, 0x46, 0x9d,
	0x32, 0xf7, 0x4e, 0xc1, 0xe0, 0xa7, 0x80, 0x18, 0x47, 0x8b, 0x7c, 0xf1, 0x67, 0xe0, 0xd0, 0xef,
	0x77, 0x04, 0xfd, 0x1c, 0x96, 0x38, 0x1c, 0xa7, 0xe2, 0x29, 0xb8, 0x39, 0x0d, 0x8f, 0x33, 0x31,
	0xe2, 0x4c, 0xb0, 0x59, 0xfc, 0x1b, 0xe7, 0x61, 0x12, 0x45, 0x93, 0x40, 0xec, 0x04, 0xff, 0x6a,
	0xc1, 0x32, 0x23, 0xa2, 0x1e, 0x44, 0x1b, 0x30, 0x98, 0xfb, 0x05, 0xc9, 0x42, 0x3f, 0xca, 0xf9,
	0x66, 0xea, 0x01, 0xb4, 0x0c, 0x9d, 0x79, 0x12, 0xf0, 0x1d, 0x95, 0x7f, 0xd1, 0x26, 0x0c, 0x0b,
	0x32, 0x4f, 0x49, 0xe6, 0x17, 0x37, 0x19, 0xe1, 0xe7, 0x26, 0x0f, 0xa1, 0x31, 0xf4, 0xe7, 0xc9,
	0x4d, 0x5c, 0x84, 0xf1, 0x95, 0xd7, 0xa5, 0x9f, 0x2b, 0xbb, 0xfc, 0x76, 0x95, 0xf9, 0xe9, 0x75,
	0x58, 0x10, 0xcf, 0x61, 0xdf, 0x84, 0x8d, 0xd6, 0xc1, 0x2d, 0x7e, 0x4c, 0xc9, 0x49, 0xe4, 0xb9,
	0xf4, 0x0b, 0xb7, 0xf0, 0xb1, 0xb8, 0xcd, 0x93, 0x20, 0x78, 0xe3, 0x17, 0xa6, 0x33, 0x51, 0x02,
	0xb1, 0xb5, 0x40, 0xf0, 0xbe, 0x0c, 0x92, 0x18, 0x0f, 0xb6, 0x11, 0x2f, 0x3e, 0x95, 0x1c, 0xdf,
	0x92, 0xb9, 0xc9, 0x51, 0xa3, 0xc5, 0x6e, 0xd0, 0x82, 0x8f, 0x60, 0x4d, 0xda, 0xc1, 0x4d, 0x6c,
	0x42, 0x92, 0xe9, 0xb3, 0x55, 0xfa, 0x14, 0x8c, 0xd3, 0xcc, 0x4f, 0x17, 0x60, 0x54, 0x34, 0xdb,
	0x2a, 0xcd, 0xf8, 0x15, 0xac, 0xd7, 0x01, 0x51, 0x86, 0x4d, 0x28, 0xf5, 0x81, 0xd8, 0xca, 0x81,
	0xfc, 0x6e, 0x01, 0x4c, 0x82, 0x20, 0x2c, 0xc2, 0x24, 0xf6, 0xa3, 0x7f, 0x76, 0x10, 0x82, 0xe1,
	0x8e, 0xf1, 0x46, 0x75, 0x17, 0xdf, 0x28, 0x67, 0xc1, 0x8d, 0x72, 0x8d, 0x37, 0xaa, 0xa7, 0x04,
	0x70, 0x06, 0xa8, 0xde, 0x7f, 0x95, 0x58, 0x7b, 0x30, 0xf4, 0xab, 0x51, 0x91, 0x5d, 0x2b, 0x3c,
	0xbb, 0xa4, 0xf9, 0xf2, 0x2c, 0xfc, 0x1c, 0x1e, 0x5e, 0xdc, 0x5c, 0x5e, 0x92, 0x3c, 0xaf, 0x70,
	0x3c, 0xe8, 0xe5, 0x6c, 0x88, 0x92, 0xd2, 0x9f, 0x09, 0x13, 0xe7, 0xf0, 0xb0, 0x2c, 0x4e, 0xe1,
	0x7b, 0x22, 0x6a, 0x53, 0xb9, 0x45, 0x56, 0xba, 0x38, 0x81, 0xdc, 0x32, 0x71, 0x2f, 0xc6, 0xa7,
	0x19, 0x67, 0x90, 0x5b, 0x74, 0xd1, 0x32, 0xf3, 0xcf, 0x02, 0x4e, 0xa0, 0x30, 0xf1, 0x1f, 0x16,
	0xac, 0xf0, 0xf2, 0x17, 0xbe, 0x27, 0xff, 0x76, 0xdd, 0x07, 0x60, 0x07, 0x31, 0x5d, 0xd3, 0x99,
	0xd9, 0x41, 0x5c, 0xda, 0x69, 0x4c, 0x97, 0x72, 0x66, 0x76, 0x1a, 0x4b, 0xfb, 0x72, 0x4c, 0xfb,
	0x72, 0x95, 0x7d, 0x51, 0xc4, 0x17, 0xf4, 0x60, 0x4a, 0xc4, 0x17, 0xd4, 0xde, 0xf3, 0xfa, 0xdc,
	0xde, 0xa3, 0xf6, 0xae, 0x37, 0xe0, 0xf6, 0x2e, 0xb5, 0x77, 0x3c, 0xe0, 0xf6, 0x0e, 0x1a, 0x81,
	0x75, 0xed, 0x0d, 0xa9, 0x69, 0x5d, 0xe3, 0x3f, 0x2d, 0x58, 0xe1, 0x85, 0xfb, 0x7e, 0x51, 0x86,
	0xe2, 0x6e, 0x96, 0x57, 0x99, 0x45, 0xdd, 0xd5, 0xa2, 0x76, 0x5a, 0xa2, 0x76, 0x4d, 0x51, 0xf7,
	0xda, 0xa2, 0xee, 0x6b, 0x51, 0x0f, 0xb4, 0xa8, 0x41, 0x8b, 0x7a, 0xa8, 0x46, 0x3d, 0x12, 0x51,
	0x5f, 0xc0, 0x0a, 0x7f, 0x71, 0xfe, 0xbb, 0xa0, 0xf1, 0x6f, 0x16, 0x74, 0x4b, 0xbc, 0x46, 0x62,
	0x33, 0x36, 0x6c, 0x8d, 0x8d, 0x4e, 0x0b, 0x1b, 0x5d, 0x13, 0x1b, 0x4e, 0x1b, 0x1b, 0xae, 0xc6,
	0x46, 0x4f, 0x63, 0xa3, 0xaf, 0xb1, 0x31, 0x50, 0xd9, 0x00, 0xc1, 0xc6, 0x0e, 0x8c, 0x18, 0x0f,
	0x3c, 0x11, 0x3f, 0x02, 0x27, 0x2f, 0x73, 0x8d, 0xa7, 0xf2, 0x50, 0x3c, 0x94, 0xe5, 0x1c, 0xf6,
	0x05, 0x4f, 0x60, 0xa9, 0xcc, 0xc8, 0xf3, 0xa9, 0x20, 0x4f, 0xda, 0xab, 0xa5, 0xee, 0xd5, 0x54,
	0x0d, 0xff, 0xaa, 0x5e, 0xd5, 0xfb, 0xc0, 0xd0, 0xd7, 0xbf, 0xa4, 0x4b, 0x74, 0x42, 0xd4, 0x28,
	0x71, 0xde, 0x85, 0x51, 0x44, 0xb2, 0x5c, 0xa4, 0x35, 0x37, 0xd5, 0x2a, 0xeb, 0x18, 0xaa, 0xac,
	0x6b, 0xac, 0xb2, 0xbd, 0xc5, 0x55, 0xb6, 0xbf, 0xa0, 0xca, 0x0e, 0xb4, 0x07, 0xe5, 0x67, 0x1b,
	0x96, 0x79, 0xea, 0xd5, 0x04, 0xe8, 0x77, 0x47, 0x22, 0xc4, 0x36, 0x11, 0xd2, 0x69, 0x27, 0xa4,
	0x6b, 0x20, 0xc4, 0x59, 0x40, 0x88, 0x6b, 0x20, 0xa4, 0x67, 0x24, 0xa4, 0xbf, 0x98, 0x90, 0xc1,
	0x02, 0x42, 0x40, 0x23, 0x04, 0xc3, 0x32, 0xcf, 0x4a, 0x23, 0x1f, 0xf8, 0x27, 0x1b, 0x3a, 0x17,
	0xe7, 0xd3, 0xff, 0x35, 0x4f, 0xcf, 0x61, 0x48, 0x19, 0xe2, 0xe9, 0xba, 0x01, 0x9d, 0x3c, 0x4e,
	0x79, 0xb2, 0x82, 0x48, 0xd6, 0xf3, 0xe9, 0xac, 0x1c, 0xc6, 0x1b, 0x00, 0x67, 0x75, 0x13, 0xac,
	0xd3, 0xb9, 0x04, 0xc3, 0x69, 0x18, 0x5f, 0x89, 0x4e, 0x17, 0xc3, 0x88, 0x99, 0x7c, 0x3a, 0x82,
	0x6e, 0x5a, 0xee, 0x8e, 0x39, 0xd0, 0xff, 0xbb, 0xbf, 0x8c, 0x00, 0xa6, 0x59, 0x72, 0x41, 0xb2,
	0x1f, 0xc2, 0x4b, 0x82, 0xb6, 0xa1, 0x5b, 0xba, 0x20, 0xc4, 0x17, 0x96, 0xe0, 0xc6, 0xab, 0xca,
	0x18, 0xc7, 0x3c, 0xa2, 0xa5, 0xa3, 0x92, 0x6f, 0x39, 0x1a, 0xf3, 0x59, 0x2d, 0xa2, 0x6e, 0xfc,
	0x48, 0x95, 0x2b, 0x02, 0xe3, 0x25, 0x8c, 0x64, 0xad, 0x57, 0x41, 0xb4, 0x08, 0xc0, 0xb1, 0xe8,
	0x44, 0x24, 0x16, 0x5e, 0xc2, 0x48, 0xd6, 0x79, 0x95, 0x7b, 0x8b, 0xf8, 0x33, 0xb8, 0xcb, 0x9a,
	0xae, 0x72, 0x6f, 0x11, 0x7a, 0x06, 0x77, 0x16, 0x2a, 0x53, 0x5b, 0xe8, 0x71, 0x1d, 0xbf, 0xa2,
	0xbf, 0xc6, 0x6b, 0x8a, 0x42, 0x11, 0xee, 0x87, 0x30, 0x94, 0x54, 0x19, 0x7a, 0xa2, 0x84, 0x2e,
	0x2b, 0xa8, 0xb6, 0xb5, 0x0f, 0x61, 0x28, 0xc9, 0xb4, 0xca, 0xb9, 0x29, 0xdd, 0x0c, 0xce, 0x92,
	0x4e, 0xab, 0x9c, 0x9b, 0xda, 0xad, 0xcd, 0xf9, 0x44, 0x12, 0x56, 0xa2, 0x03, 0x7e, 0xac, 0x9c,
	0x7c, 0x2d, 0xae, 0xc6, 0x4f, 0x9a, 0xdd, 0xa3, 0xc0, 0x39, 0x96, 0xb4, 0x98, 0x8e, 0xa3, 0x8b,
	0xb4, 0xf1, 0xba, 0x60, 0x50, 0x6b, 0x35, 0xbf, 0x84, 0x01, 0x0b, 0xf9, 0x8d, 0x5f, 0x68, 0xa7,
	0xaf, 0x88, 0xa5, 0x3b, 0x00, 0x24, 0x41, 0x0b, 0x40, 0x72, 0xeb, 0x0e, 0x5e, 0x01, 0xb0, 0xe9,
	0x6f, 0xc9, 0x3c, 0x6d, 0x22, 0xd4, 0x8a, 0xc9, 0x88, 0x30, 0x11, 0x08, 0xa5, 0x28, 0x42, 0x1f,
	0x34, 0xf7, 0x50, 0x49, 0xa5, 0xdb, 0x21, 0x4a, 0x4d, 0xd4, 0x84, 0x90, 0x94, 0x92, 0x11, 0xe2,
	0x2b, 0x91, 0x4a, 0x4c, 0x12, 0xa1, 0x0f, 0x1b, 0x91, 0xc8, 0x52, 0xc9, 0x08, 0xb3, 0x0f, 0x7d,
	0xd1, 0xe1, 0xa3, 0x75, 0x29, 0x1f, 0xa4, 0x96, 0xbf, 0xaa, 0x26, 0x4a, 0xaf, 0x72, 0x00, 0x50,
	0x37, 0xe9, 0xc8, 0x53, 0x93, 0xa1, 0x6e, 0xee, 0xda, 0x6e, 0xe4, 0x81, 0x88, 0x5e, 0x71, 0x6d,
	0x34, 0xc3, 0x06, 0xd7, 0xba, 0x7f, 0xac, 0x5c, 0x1b, 0x2d, 0x65, 0x9b, 0xeb, 0x2e, 0xb8, 0xac,
	0x73, 0x42, 0x6b, 0x52, 0x9c, 0xd5, 0x83, 0x37, 0x46, 0x52, 0x01, 0xaf, 0xd9, 0x19, 0x54, 0x9d,
	0x92, 0x76, 0xd9, 0x25, 0xcf, 0x96, 0xc5, 0xf6, 0xc5, 0x35, 0x95, 0x1d, 0xf5, 0x9e, 0xc3, 0xe0,
	0x58, 0x3d, 0xc5, 0x95, 0xa3, 0xfe, 0x38, 0xb7, 0x38, 0x1e, 0xc1, 0xb7, 0xfd, 0xad, 0xed, 0x43,
	0x3a, 0xfc, 0x9d, 0x4b, 0x7f, 0xf6, 0xfe, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x23, 0xde, 0x81, 0x2e,
	0xc9, 0x13, 0x00, 0x00,
}
